<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto\MplTransaction;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.MplTransaction.Sales</code>
 */
class Sales extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 Status = 1;</code>
     */
    protected $Status = 0;
    /**
     * Generated from protobuf field <code>uint64 Amount = 2 [jstype = JS_STRING];</code>
     */
    protected $Amount = 0;
    /**
     * Generated from protobuf field <code>string CardNumber = 3;</code>
     */
    protected $CardNumber = '';
    /**
     * Generated from protobuf field <code>string MerchantName = 4;</code>
     */
    protected $MerchantName = '';
    /**
     * Generated from protobuf field <code>uint64 OrderId = 5 [jstype = JS_STRING];</code>
     */
    protected $OrderId = 0;
    /**
     * Generated from protobuf field <code>uint64 RequestDateTime = 6 [jstype = JS_STRING];</code>
     */
    protected $RequestDateTime = 0;
    /**
     * Generated from protobuf field <code>uint64 RRN = 7 [jstype = JS_STRING];</code>
     */
    protected $RRN = 0;
    /**
     * Generated from protobuf field <code>string StatusDescription = 8;</code>
     */
    protected $StatusDescription = '';
    /**
     * Generated from protobuf field <code>uint32 TerminalNo = 9;</code>
     */
    protected $TerminalNo = 0;
    /**
     * Generated from protobuf field <code>uint32 TraceNo = 10;</code>
     */
    protected $TraceNo = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Status
     *     @type int|string $Amount
     *     @type string $CardNumber
     *     @type string $MerchantName
     *     @type int|string $OrderId
     *     @type int|string $RequestDateTime
     *     @type int|string $RRN
     *     @type string $StatusDescription
     *     @type int $TerminalNo
     *     @type int $TraceNo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBGlobal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 Status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * Generated from protobuf field <code>uint32 Status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->Status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 Amount = 2 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->Amount;
    }

    /**
     * Generated from protobuf field <code>uint64 Amount = 2 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkUint64($var);
        $this->Amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CardNumber = 3;</code>
     * @return string
     */
    public function getCardNumber()
    {
        return $this->CardNumber;
    }

    /**
     * Generated from protobuf field <code>string CardNumber = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCardNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->CardNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string MerchantName = 4;</code>
     * @return string
     */
    public function getMerchantName()
    {
        return $this->MerchantName;
    }

    /**
     * Generated from protobuf field <code>string MerchantName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantName($var)
    {
        GPBUtil::checkString($var, True);
        $this->MerchantName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 OrderId = 5 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getOrderId()
    {
        return $this->OrderId;
    }

    /**
     * Generated from protobuf field <code>uint64 OrderId = 5 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkUint64($var);
        $this->OrderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 RequestDateTime = 6 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getRequestDateTime()
    {
        return $this->RequestDateTime;
    }

    /**
     * Generated from protobuf field <code>uint64 RequestDateTime = 6 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setRequestDateTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->RequestDateTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 RRN = 7 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getRRN()
    {
        return $this->RRN;
    }

    /**
     * Generated from protobuf field <code>uint64 RRN = 7 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setRRN($var)
    {
        GPBUtil::checkUint64($var);
        $this->RRN = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string StatusDescription = 8;</code>
     * @return string
     */
    public function getStatusDescription()
    {
        return $this->StatusDescription;
    }

    /**
     * Generated from protobuf field <code>string StatusDescription = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setStatusDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->StatusDescription = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 TerminalNo = 9;</code>
     * @return int
     */
    public function getTerminalNo()
    {
        return $this->TerminalNo;
    }

    /**
     * Generated from protobuf field <code>uint32 TerminalNo = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setTerminalNo($var)
    {
        GPBUtil::checkUint32($var);
        $this->TerminalNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 TraceNo = 10;</code>
     * @return int
     */
    public function getTraceNo()
    {
        return $this->TraceNo;
    }

    /**
     * Generated from protobuf field <code>uint32 TraceNo = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setTraceNo($var)
    {
        GPBUtil::checkUint32($var);
        $this->TraceNo = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Sales::class, \Proto\MplTransaction_Sales::class);

