<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto\MplTransaction;

use UnexpectedValueException;

/**
 * Protobuf type <code>proto.MplTransaction.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * Generated from protobuf enum <code>BILL = 1;</code>
     */
    const BILL = 1;
    /**
     * Generated from protobuf enum <code>TOPUP = 2;</code>
     */
    const TOPUP = 2;
    /**
     * Generated from protobuf enum <code>SALES = 3;</code>
     */
    const SALES = 3;
    /**
     * Generated from protobuf enum <code>CARD_TO_CARD = 4;</code>
     */
    const CARD_TO_CARD = 4;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::BILL => 'BILL',
        self::TOPUP => 'TOPUP',
        self::SALES => 'SALES',
        self::CARD_TO_CARD => 'CARD_TO_CARD',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Proto\MplTransaction_Type::class);

