#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('AMADAY_START', microtime(true));

require __DIR__ . '/vendor/autoload.php';

$status = (require_once __DIR__ . '/app/Core/Bootstrap/app.php')
    ->handleCommand(new ArgvInput());

exit($status);