version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./storage:/usr/local/lib/php/extensions/no-debug-non-zts-20230831
    command: [ "ls", "-l", "/" ]
