<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientGetDifference.proto

namespace Proto\Updatequeue;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.updatequeue.ClientGetDifference</code>
 */
class ClientGetDifference extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     */
    protected $request = null;
    /**
     * Generated from protobuf field <code>uint64 pts = 2;</code>
     */
    protected $pts = 0;
    /**
     * Generated from protobuf field <code>uint64 seq = 3;</code>
     */
    protected $seq = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Request $request
     *     @type int|string $pts
     *     @type int|string $seq
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ClientGetDifference::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @return \Proto\Request|null
     */
    public function getRequest()
    {
        return $this->request;
    }

    public function hasRequest()
    {
        return isset($this->request);
    }

    public function clearRequest()
    {
        unset($this->request);
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @param \Proto\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Proto\Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 pts = 2;</code>
     * @return int|string
     */
    public function getPts()
    {
        return $this->pts;
    }

    /**
     * Generated from protobuf field <code>uint64 pts = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPts($var)
    {
        GPBUtil::checkUint64($var);
        $this->pts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 seq = 3;</code>
     * @return int|string
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Generated from protobuf field <code>uint64 seq = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint64($var);
        $this->seq = $var;

        return $this;
    }

}

