<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientGetDifference.proto

namespace Proto\Updatequeue;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.updatequeue.ClientGetDifferenceResponse</code>
 */
class ClientGetDifferenceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    protected $response = null;
    /**
     * Generated from protobuf field <code>.proto.updatequeue.ClientUpdates updates = 2;</code>
     */
    protected $updates = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type \Proto\Updatequeue\ClientUpdates $updates
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ClientGetDifference::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response|null
     */
    public function getResponse()
    {
        return $this->response;
    }

    public function hasResponse()
    {
        return isset($this->response);
    }

    public function clearResponse()
    {
        unset($this->response);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.updatequeue.ClientUpdates updates = 2;</code>
     * @return \Proto\Updatequeue\ClientUpdates|null
     */
    public function getUpdates()
    {
        return $this->updates;
    }

    public function hasUpdates()
    {
        return isset($this->updates);
    }

    public function clearUpdates()
    {
        unset($this->updates);
    }

    /**
     * Generated from protobuf field <code>.proto.updatequeue.ClientUpdates updates = 2;</code>
     * @param \Proto\Updatequeue\ClientUpdates $var
     * @return $this
     */
    public function setUpdates($var)
    {
        GPBUtil::checkMessage($var, \Proto\Updatequeue\ClientUpdates::class);
        $this->updates = $var;

        return $this;
    }

}

