<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientUpdates.proto

namespace Proto\Updatequeue;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.updatequeue.ClientUpdates</code>
 */
class ClientUpdates extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 user_id = 1;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>uint64 room_id = 2;</code>
     */
    protected $room_id = 0;
    /**
     * Generated from protobuf field <code>uint64 last_pts = 3;</code>
     */
    protected $last_pts = 0;
    /**
     * Generated from protobuf field <code>uint32 pts_count = 4;</code>
     */
    protected $pts_count = 0;
    /**
     * Generated from protobuf field <code>repeated .proto.updatequeue.Update updates = 5;</code>
     */
    private $updates;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_id
     *     @type int|string $room_id
     *     @type int|string $last_pts
     *     @type int $pts_count
     *     @type array<\Proto\Updatequeue\Update>|\Google\Protobuf\Internal\RepeatedField $updates
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ClientUpdates::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 room_id = 2;</code>
     * @return int|string
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * Generated from protobuf field <code>uint64 room_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkUint64($var);
        $this->room_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 last_pts = 3;</code>
     * @return int|string
     */
    public function getLastPts()
    {
        return $this->last_pts;
    }

    /**
     * Generated from protobuf field <code>uint64 last_pts = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastPts($var)
    {
        GPBUtil::checkUint64($var);
        $this->last_pts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 pts_count = 4;</code>
     * @return int
     */
    public function getPtsCount()
    {
        return $this->pts_count;
    }

    /**
     * Generated from protobuf field <code>uint32 pts_count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPtsCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->pts_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.updatequeue.Update updates = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUpdates()
    {
        return $this->updates;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.updatequeue.Update updates = 5;</code>
     * @param array<\Proto\Updatequeue\Update>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUpdates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Updatequeue\Update::class);
        $this->updates = $arr;

        return $this;
    }

}

