<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientCondition.proto

namespace Proto\ClientCondition\Room;

use UnexpectedValueException;

/**
 * Protobuf type <code>proto.ClientCondition.Room.OfflineMute</code>
 */
class OfflineMute
{
    /**
     * Generated from protobuf enum <code>UNCHANGED = 0;</code>
     */
    const UNCHANGED = 0;
    /**
     * Generated from protobuf enum <code>MUTED = 1;</code>
     */
    const MUTED = 1;
    /**
     * Generated from protobuf enum <code>UNMUTED = 2;</code>
     */
    const UNMUTED = 2;

    private static $valueToName = [
        self::UNCHANGED => 'UNCHANGED',
        self::MUTED => 'MUTED',
        self::UNMUTED => 'UNMUTED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(OfflineMute::class, \Proto\ClientCondition_Room_OfflineMute::class);

