<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BillInquiryTelecom.proto

namespace Proto\BillInquiryTelecomResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.BillInquiryTelecomResponse.BillInfo</code>
 */
class BillInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 bill_id = 1;</code>
     */
    protected $bill_id = 0;
    /**
     * Generated from protobuf field <code>uint64 pay_id = 2;</code>
     */
    protected $pay_id = 0;
    /**
     * Generated from protobuf field <code>uint64 amount = 3;</code>
     */
    protected $amount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $bill_id
     *     @type int|string $pay_id
     *     @type int|string $amount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BillInquiryTelecom::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 bill_id = 1;</code>
     * @return int|string
     */
    public function getBillId()
    {
        return $this->bill_id;
    }

    /**
     * Generated from protobuf field <code>uint64 bill_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBillId($var)
    {
        GPBUtil::checkUint64($var);
        $this->bill_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 pay_id = 2;</code>
     * @return int|string
     */
    public function getPayId()
    {
        return $this->pay_id;
    }

    /**
     * Generated from protobuf field <code>uint64 pay_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPayId($var)
    {
        GPBUtil::checkUint64($var);
        $this->pay_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 amount = 3;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>uint64 amount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkUint64($var);
        $this->amount = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(BillInfo::class, \Proto\BillInquiryTelecomResponse_BillInfo::class);

