<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StoryGetStories.proto

namespace Proto\GroupedStories;

use UnexpectedValueException;

/**
 * Protobuf type <code>proto.GroupedStories.Originator</code>
 */
class Originator
{
    /**
     * Generated from protobuf enum <code>User = 0;</code>
     */
    const User = 0;
    /**
     * Generated from protobuf enum <code>Room = 1;</code>
     */
    const Room = 1;

    private static $valueToName = [
        self::User => 'User',
        self::Room => 'Room',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Originator::class, \Proto\GroupedStories_Originator::class);

