<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto\RoomMessageWallet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.RoomMessageWallet.CardToCard</code>
 */
class CardToCard extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 from_user_id = 1 [jstype = JS_STRING];</code>
     */
    protected $from_user_id = 0;
    /**
     * Generated from protobuf field <code>uint64 to_user_id = 2 [jstype = JS_STRING];</code>
     */
    protected $to_user_id = 0;
    /**
     * Generated from protobuf field <code>uint64 order_id = 3 [jstype = JS_STRING];</code>
     */
    protected $order_id = 0;
    /**
     * Generated from protobuf field <code>string token = 4;</code>
     */
    protected $token = '';
    /**
     * Generated from protobuf field <code>uint64 amount = 5 [jstype = JS_STRING];</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>string source_card_number = 6;</code>
     */
    protected $source_card_number = '';
    /**
     * Generated from protobuf field <code>string dest_card_number = 7;</code>
     */
    protected $dest_card_number = '';
    /**
     * Generated from protobuf field <code>uint32 request_time = 8;</code>
     */
    protected $request_time = 0;
    /**
     * Generated from protobuf field <code>string rrn = 9;</code>
     */
    protected $rrn = '';
    /**
     * Generated from protobuf field <code>string trace_number = 10;</code>
     */
    protected $trace_number = '';
    /**
     * Generated from protobuf field <code>string bankName = 11;</code>
     */
    protected $bankName = '';
    /**
     * Generated from protobuf field <code>string destBankName = 12;</code>
     */
    protected $destBankName = '';
    /**
     * Generated from protobuf field <code>string cardOwnerName = 13;</code>
     */
    protected $cardOwnerName = '';
    /**
     * Generated from protobuf field <code>bool status = 14;</code>
     */
    protected $status = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $from_user_id
     *     @type int|string $to_user_id
     *     @type int|string $order_id
     *     @type string $token
     *     @type int|string $amount
     *     @type string $source_card_number
     *     @type string $dest_card_number
     *     @type int $request_time
     *     @type string $rrn
     *     @type string $trace_number
     *     @type string $bankName
     *     @type string $destBankName
     *     @type string $cardOwnerName
     *     @type bool $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBGlobal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 from_user_id = 1 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getFromUserId()
    {
        return $this->from_user_id;
    }

    /**
     * Generated from protobuf field <code>uint64 from_user_id = 1 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setFromUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->from_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 to_user_id = 2 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getToUserId()
    {
        return $this->to_user_id;
    }

    /**
     * Generated from protobuf field <code>uint64 to_user_id = 2 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setToUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->to_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 order_id = 3 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Generated from protobuf field <code>uint64 order_id = 3 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkUint64($var);
        $this->order_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token = 4;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 amount = 5 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>uint64 amount = 5 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkUint64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source_card_number = 6;</code>
     * @return string
     */
    public function getSourceCardNumber()
    {
        return $this->source_card_number;
    }

    /**
     * Generated from protobuf field <code>string source_card_number = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceCardNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_card_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dest_card_number = 7;</code>
     * @return string
     */
    public function getDestCardNumber()
    {
        return $this->dest_card_number;
    }

    /**
     * Generated from protobuf field <code>string dest_card_number = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDestCardNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->dest_card_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 request_time = 8;</code>
     * @return int
     */
    public function getRequestTime()
    {
        return $this->request_time;
    }

    /**
     * Generated from protobuf field <code>uint32 request_time = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setRequestTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->request_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rrn = 9;</code>
     * @return string
     */
    public function getRrn()
    {
        return $this->rrn;
    }

    /**
     * Generated from protobuf field <code>string rrn = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setRrn($var)
    {
        GPBUtil::checkString($var, True);
        $this->rrn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trace_number = 10;</code>
     * @return string
     */
    public function getTraceNumber()
    {
        return $this->trace_number;
    }

    /**
     * Generated from protobuf field <code>string trace_number = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setTraceNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->trace_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bankName = 11;</code>
     * @return string
     */
    public function getBankName()
    {
        return $this->bankName;
    }

    /**
     * Generated from protobuf field <code>string bankName = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setBankName($var)
    {
        GPBUtil::checkString($var, True);
        $this->bankName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string destBankName = 12;</code>
     * @return string
     */
    public function getDestBankName()
    {
        return $this->destBankName;
    }

    /**
     * Generated from protobuf field <code>string destBankName = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setDestBankName($var)
    {
        GPBUtil::checkString($var, True);
        $this->destBankName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cardOwnerName = 13;</code>
     * @return string
     */
    public function getCardOwnerName()
    {
        return $this->cardOwnerName;
    }

    /**
     * Generated from protobuf field <code>string cardOwnerName = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setCardOwnerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->cardOwnerName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool status = 14;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>bool status = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->status = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CardToCard::class, \Proto\RoomMessageWallet_CardToCard::class);

