<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BillInquiryTelecom.proto

namespace GPBMetadata;

class BillInquiryTelecom
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
é
BillInquiryTelecom.protoprotoResponse.proto"f
BillInquiryTelecom
request (2.proto.Request
province_code (
telephone_number ("š
BillInquiryTelecomResponse!
response (2.proto.Response
status (
message (	<
mid_term (2*.proto.BillInquiryTelecomResponse.BillInfo=
	last_term (2*.proto.BillInquiryTelecomResponse.BillInfo;
BillInfo
bill_id (
pay_id (
amount (B)
net.iGap.protoBProtoBillInquiryTelecombproto3'
        , true);

        static::$is_initialized = true;
    }
}

