<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelDelete.proto

namespace GPBMetadata;

class ChannelDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
ê
ChannelDelete.protoprotoResponse.proto"A
ChannelDelete
request (2.proto.Request
room_id ("K
ChannelDeleteResponse!
response (2.proto.Response
room_id (B$
net.iGap.protoBProtoChannelDeletebproto3'
        , true);

        static::$is_initialized = true;
    }
}

