<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelRemoveUsername.proto

namespace GPBMetadata;

class ChannelRemoveUsername
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
Š
ChannelRemoveUsername.protoprotoResponse.proto"I
ChannelRemoveUsername
request (2.proto.Request
room_id ("S
ChannelRemoveUsernameResponse!
response (2.proto.Response
room_id (B,
net.iGap.protoBProtoChannelRemoveUsernamebproto3'
        , true);

        static::$is_initialized = true;
    }
}

