<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelRevokeLink.proto

namespace GPBMetadata;

class ChannelRevokeLink
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
¥
ChannelRevokeLink.protoprotoResponse.proto"E
ChannelRevokeLink
request (2.proto.Request
room_id ("z
ChannelRevokeLinkResponse!
response (2.proto.Response
room_id (
invite_link (	
invite_token (	B(
net.iGap.protoBProtoChannelRevokeLinkbproto3'
        , true);

        static::$is_initialized = true;
    }
}

