<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelCreate.proto

namespace GPBMetadata;

class ChannelCreate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
‘
ChannelCreate.protoprotoResponse.proto"S
ChannelCreate
request (2.proto.Request
name (	
description (	"`
ChannelCreateResponse!
response (2.proto.Response
room_id (
invite_link (	B$
net.iGap.protoBProtoChannelCreatebproto3'
        , true);

        static::$is_initialized = true;
    }
}

