<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelUpdateSignature.proto

namespace GPBMetadata;

class ChannelUpdateSignature
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
´
ChannelUpdateSignature.protoprotoResponse.proto"]
ChannelUpdateSignature
request (2.proto.Request
room_id (
	signature ("g
ChannelUpdateSignatureResponse!
response (2.proto.Response
room_id (
	signature (B-
net.iGap.protoBProtoChannelUpdateSignaturebproto3'
        , true);

        static::$is_initialized = true;
    }
}

