<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatClearMessage.proto

namespace GPBMetadata;

class ChatClearMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
á
ChatClearMessage.protoprotoResponse.proto"y
ChatClearMessage
request (2.proto.Request
room_id (
clear_message_id (
clear_document_id ("ƒ
ChatClearMessageResponse!
response (2.proto.Response
room_id (
clear_message_id (
clear_document_id (B\'
net.iGap.protoBProtoChatClearMessagebproto3'
        , true);

        static::$is_initialized = true;
    }
}

