<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatSetAction.proto

namespace GPBMetadata;

class ChatSetAction
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
Á
ChatSetAction.protoprotoResponse.protoGlobal.proto"y
ChatSetAction
request (2.proto.Request
room_id (#
action (2.proto.ClientAction
	action_id ("Å
ChatSetActionResponse!
response (2.proto.Response
room_id (#
action (2.proto.ClientAction
user_id (B$
net.iGap.protoBProtoChatSetActionbproto3'
        , true);

        static::$is_initialized = true;
    }
}

