<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientGetDifference.proto

namespace GPBMetadata;

class ClientGetDifference
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\ClientUpdates::initOnce();
        $pool->internalAddGeneratedFile(
            '
Î
ClientGetDifference.protoproto.updatequeueResponse.protoClientUpdates.proto"P
ClientGetDifference
request (2.proto.Request
pts (
seq ("s
ClientGetDifferenceResponse!
response (2.proto.Response1
updates (2 .proto.updatequeue.ClientUpdatesB*
net.iGap.protoBProtoClientGetDifferencebproto3'
        , true);

        static::$is_initialized = true;
    }
}

