<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientUpdate.proto

namespace GPBMetadata;

class ClientUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¢
ClientUpdate.protoproto.updatequeue"L
Update
pts (
seq (
	action_id (
wrapped_proto (B#
net.iGap.protoBProtoClientUpdatebproto3'
        , true);

        static::$is_initialized = true;
    }
}

