<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientGetState.proto

namespace GPBMetadata;

class ClientGetState
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
å
ClientGetState.protoproto.updatequeueResponse.proto"1
ClientGetState
request (2.proto.Request"H
ClientGetStateResponse!
response (2.proto.Response
pts (B%
net.iGap.protoBProtoClientGetStatebproto3'
        , true);

        static::$is_initialized = true;
    }
}

