<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientSetPollItemClick.proto

namespace GPBMetadata;

class ClientSetPollItemClick
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
ý
ClientSetPollItemClick.protoprotoResponse.proto"J
ClientSetPollItemClick
request (2.proto.Request
item_id ("C
ClientSetPollItemClickResponse!
response (2.proto.ResponseB-
net.iGap.protoBProtoClientSetPollItemClickbproto3'
        , true);

        static::$is_initialized = true;
    }
}

