<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientSetDiscoveryItemAgreement.proto

namespace GPBMetadata;

class ClientSetDiscoveryItemAgreement
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
¡
%ClientSetDiscoveryItemAgreement.protoprotoResponse.proto"S
ClientSetDiscoveryItemAgreement
request (2.proto.Request
item_id ("L
\'ClientSetDiscoveryItemAgreementResponse!
response (2.proto.ResponseB6
net.iGap.protoB$ProtoClientSetDiscoveryItemAgreementbproto3'
        , true);

        static::$is_initialized = true;
    }
}

