<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientSetDiscoveryItemClick.proto

namespace GPBMetadata;

class ClientSetDiscoveryItemClick
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
‘
!ClientSetDiscoveryItemClick.protoprotoResponse.proto"O
ClientSetDiscoveryItemClick
request (2.proto.Request
item_id ("H
#ClientSetDiscoveryItemClickResponse!
response (2.proto.ResponseB2
net.iGap.protoB ProtoClientSetDiscoveryItemClickbproto3'
        , true);

        static::$is_initialized = true;
    }
}

