<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientGetFavoriteMenu.proto

namespace GPBMetadata;

class ClientGetFavoriteMenu
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
š
ClientGetFavoriteMenu.protoprotoResponse.protoGlobal.proto"8
ClientGetFavoriteMenu
request (2.proto.Request"f
ClientGetFavoriteMenuResponse!
response (2.proto.Response"
	favorites (2.proto.FavoriteB,
net.iGap.protoBProtoClientGetFavoriteMenubproto3'
        , true);

        static::$is_initialized = true;
    }
}

