<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientRoomChangeOwner.proto

namespace GPBMetadata;

class ClientRoomChangeOwner
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
ý
ClientRoomChangeOwner.protoprotoResponse.protoGlobal.proto"Z
ClientRoomChangeOwner
request (2.proto.Request
user_id (
room_id ("¦
ClientRoomChangeOwnerResponse!
response (2.proto.Response
old_owner_id (
room_id (%

permission (2.proto.RoomAccess
new_owner_id (B,
net.iGap.protoBProtoClientRoomChangeOwnerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

