<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientGetDiscovery.proto

namespace GPBMetadata;

class ClientGetDiscovery
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ö
ClientGetDiscovery.protoprotoResponse.protoGlobal.proto"k
ClientGetDiscovery
request (2.proto.Request
page_id (

project_id (
item_id ("u
ClientGetDiscoveryResponse!
response (2.proto.Response
title (	%
discoveries (2.proto.DiscoveryB)
net.iGap.protoBProtoClientGetDiscoverybproto3'
        , true);

        static::$is_initialized = true;
    }
}

