<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Error.proto

namespace GPBMetadata;

class Error
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ñ
Error.protoproto"”
ErrorResponse!
response (2.proto.Response

major_code (

minor_code (
wait (
message (	
request_action_id (B
net.iGap.protoB
ProtoErrorbproto3'
        , true);

        static::$is_initialized = true;
    }
}

