<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FileUploadOption.proto

namespace GPBMetadata;

class FileUploadOption
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
°
FileUploadOption.protoprotoResponse.proto"A
FileUploadOption
request (2.proto.Request
size ("Š
FileUploadOptionResponse!
response (2.proto.Response
first_bytes_limit (
last_bytes_limit (
max_connection (B\'
net.iGap.protoBProtoFileUploadOptionbproto3'
        , true);

        static::$is_initialized = true;
    }
}

