<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GeoUpdateComment.proto

namespace GPBMetadata;

class GeoUpdateComment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
ö
GeoUpdateComment.protoprotoResponse.proto"D
GeoUpdateComment
request (2.proto.Request
comment (	"N
GeoUpdateCommentResponse!
response (2.proto.Response
comment (	B\'
net.iGap.protoBProtoGeoUpdateCommentbproto3'
        , true);

        static::$is_initialized = true;
    }
}

