<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupKickMember.proto

namespace GPBMetadata;

class GroupKickMember
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
˜
GroupKickMember.protoprotoResponse.proto"V
GroupKickMember
request (2.proto.Request
room_id (
	member_id ("`
GroupKickMemberResponse!
response (2.proto.Response
room_id (
	member_id (B&
net.iGap.protoBProtoGroupKickMemberbproto3'
        , true);

        static::$is_initialized = true;
    }
}

