<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupChangeMemberRights.proto

namespace GPBMetadata;

class GroupChangeMemberRights
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
è
GroupChangeMemberRights.protoprotoResponse.proto"Í
GroupChangeMemberRights
request (2.proto.Request
room_id (
user_id (?

permission (2+.proto.GroupChangeMemberRights.MemberRights­
MemberRights
	send_text (

send_media (
send_gif (
send_sticker (
	send_link (
pin_message (

add_member (

get_member	 ("§
GroupChangeMemberRightsResponse!
response (2.proto.Response
room_id (
user_id (?

permission (2+.proto.GroupChangeMemberRights.MemberRightsB.
net.iGap.protoBProtoGroupChangeMemberRightsbproto3'
        , true);

        static::$is_initialized = true;
    }
}

