<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupRevokeLink.proto

namespace GPBMetadata;

class GroupRevokeLink
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
ù
GroupRevokeLink.protoprotoResponse.proto"C
GroupRevokeLink
request (2.proto.Request
room_id ("x
GroupRevokeLinkResponse!
response (2.proto.Response
room_id (
invite_link (	
invite_token (	B&
net.iGap.protoBProtoGroupRevokeLinkbproto3'
        , true);

        static::$is_initialized = true;
    }
}

