<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupLeft.proto

namespace GPBMetadata;

class GroupLeft
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
í
GroupLeft.protoprotoResponse.proto"=
	GroupLeft
request (2.proto.Request
room_id ("Z
GroupLeftResponse!
response (2.proto.Response
room_id (
	member_id (B 
net.iGap.protoBProtoGroupLeftbproto3'
        , true);

        static::$is_initialized = true;
    }
}

