<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupAddMember.proto

namespace GPBMetadata;

class GroupAddMember
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
²
GroupAddMember.protoprotoResponse.protoGlobal.proto"À
GroupAddMember
request (2.proto.Request
room_id (,
member (2.proto.GroupAddMember.MemberN
Member
user_id (
start_message_id (
start_document_id ("‚
GroupAddMemberResponse!
response (2.proto.Response
room_id (
user_id (#
role (2.proto.GroupRoom.RoleB%
net.iGap.protoBProtoGroupAddMemberbproto3'
        , true);

        static::$is_initialized = true;
    }
}

