<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupSendMessage.proto

namespace GPBMetadata;

class GroupSendMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
µ
GroupSendMessage.protoprotoResponse.protoGlobal.proto"Ê
GroupSendMessage
request (2.proto.Request,
message_type (2.proto.RoomMessageType
room_id (
message (	

attachment (	,
location (2.proto.RoomMessageLocation*
contact (2.proto.RoomMessageContact
reply_to (3
forward_from	 (2.proto.RoomMessageForwardFrom
	random_id
 (
additional_type (
additional_data (	1
story_reply (2.proto.RoomMessageStoryReply5
story_forward (2.proto.RoomMessageStoryForward 
mentions (2.proto.Mention*
sticker (2.proto.RoomMessageSticker2
card_to_card (2.proto.RoomMessageCardToCard9
bot_action_lists (2.proto.RoomMessageBotActionList$

text_signs (2.proto.TextSigns"x
GroupSendMessageResponse!
response (2.proto.Response
room_id ((
room_message (2.proto.RoomMessageB\'
net.iGap.protoBProtoGroupSendMessagebproto3'
        , true);

        static::$is_initialized = true;
    }
}

