<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupEdit.proto

namespace GPBMetadata;

class GroupEdit
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
 
GroupEdit.protoprotoResponse.proto"`
	GroupEdit
request (2.proto.Request
room_id (
name (	
description (	"j
GroupEditResponse!
response (2.proto.Response
room_id (
name (	
description (	B 
net.iGap.protoBProtoGroupEditbproto3'
        , true);

        static::$is_initialized = true;
    }
}

