<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupAvatarDelete.proto

namespace GPBMetadata;

class GroupAvatarDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
’
GroupAvatarDelete.protoprotoResponse.proto"Q
GroupAvatarDelete
request (2.proto.Request

id (
room_id ("[
GroupAvatarDeleteResponse!
response (2.proto.Response

id (
room_id (B(
net.iGap.protoBProtoGroupAvatarDeletebproto3'
        , true);

        static::$is_initialized = true;
    }
}

