<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupCreate.proto

namespace GPBMetadata;

class GroupCreate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
‰
GroupCreate.protoprotoResponse.proto"Q
GroupCreate
request (2.proto.Request
name (	
description (	"^
GroupCreateResponse!
response (2.proto.Response
room_id (
invite_link (	B"
net.iGap.protoBProtoGroupCreatebproto3'
        , true);

        static::$is_initialized = true;
    }
}

