<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupAvatarGetList.proto

namespace GPBMetadata;

class GroupAvatarGetList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
š
GroupAvatarGetList.protoprotoResponse.protoGlobal.proto"F
GroupAvatarGetList
request (2.proto.Request
room_id ("^
GroupAvatarGetListResponse!
response (2.proto.Response
avatar (2.proto.AvatarB)
net.iGap.protoBProtoGroupAvatarGetListbproto3'
        , true);

        static::$is_initialized = true;
    }
}

