<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InfoUpdate.proto

namespace GPBMetadata;

class InfoUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
‹
InfoUpdate.protoprotoResponse.proto"X

InfoUpdate
request (2.proto.Request
app_id (
app_build_version ("[
InfoUpdateResponse!
response (2.proto.Response
body (	
last_version (B!
net.iGap.protoBProtoInfoUpdatebproto3'
        , true);

        static::$is_initialized = true;
    }
}

