<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InfoPage.proto

namespace GPBMetadata;

class InfoPage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
Î
InfoPage.protoprotoResponse.proto"7
InfoPage
request (2.proto.Request

id (	"C
InfoPageResponse!
response (2.proto.Response
body (	B
net.iGap.protoBProtoInfoPagebproto3'
        , true);

        static::$is_initialized = true;
    }
}

