<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageContainer.proto

namespace GPBMetadata;

class MessageContainer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
­
MessageContainer.protoproto"[
MessageContainer

id (	
	action_id (
	timestamp (
wrapped_proto (B\'
net.iGap.protoBProtoMessageContainerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

