<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MplSetCardToCardResult.proto

namespace GPBMetadata;

class MplSetCardToCardResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ž
MplSetCardToCardResult.protoprotoResponse.proto"[
MplSetCardToCardResult
request (2.proto.Request
data (	

to_user_id ("C
MplSetCardToCardResultResponse!
response (2.proto.ResponseB-
net.iGap.protoBProtoMplSetCardToCardResultbproto3'
        , true);

        static::$is_initialized = true;
    }
}

