<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MplSalesList.proto

namespace GPBMetadata;

class MplSalesList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
¾
MplSalesList.protoprotoResponse.protoGlobal.proto"}
MplSalesList
request (2.proto.Request%
status (2.proto.MplSale.Status%

pagination (2.proto.Pagination"W
MplSalesListResponse!
response (2.proto.Response
sale (2.proto.MplSaleB#
net.iGap.protoBProtoMplSalesListbproto3'
        , true);

        static::$is_initialized = true;
    }
}

