<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MxbUserInsertion.proto

namespace GPBMetadata;

class MxbUserInsertion
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\Request::initOnce();
        $pool->internalAddGeneratedFile(
            '
ø
MxbUserInsertion.protoprotoRequest.proto"X
MxbUserInsertion
request (2.proto.Request
messenger_id (
phone (	"=
MxbUserInsertionResponse!
response (2.proto.ResponseB\'
net.iGap.protoBProtoMxbUserInsertionbproto3'
        , true);

        static::$is_initialized = true;
    }
}

