<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PushTwoStepVerification.proto

namespace GPBMetadata;

class PushTwoStepVerification
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ü
PushTwoStepVerification.protoproto"|
PushTwoStepVerificationResponse!
response (2.proto.Response
username (	
user_id (
author_hash (	B.
net.iGap.protoBProtoPushTwoStepVerificationbproto3'
        , true);

        static::$is_initialized = true;
    }
}

