<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PushLoginToken.proto

namespace GPBMetadata;

class PushLoginToken
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ñ
PushLoginToken.protoproto"‚
PushLoginTokenResponse!
response (2.proto.Response
username (	
user_id (
author_hash (	
token (	B%
net.iGap.protoBProtoPushLoginTokenbproto3'
        , true);

        static::$is_initialized = true;
    }
}

