<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PushUserInfoExpired.proto

namespace GPBMetadata;

class PushUserInfoExpired
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
©
PushUserInfoExpired.protoproto"Q
PushUserInfoExpiredResponse!
response (2.proto.Response
user_id (B*
net.iGap.protoBProtoPushUserInfoExpiredbproto3'
        , true);

        static::$is_initialized = true;
    }
}

