<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalingRate.proto

namespace GPBMetadata;

class SignalingRate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
ò
SignalingRate.protoprotoResponse.proto"Z
SignalingRate
request (2.proto.Request

id (
rate (
reason (	":
SignalingRateResponse!
response (2.proto.ResponseB$
net.iGap.protoBProtoSignalingRatebproto3'
        , true);

        static::$is_initialized = true;
    }
}

