<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalingGetConfiguration.proto

namespace GPBMetadata;

class SignalingGetConfiguration
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ü
SignalingGetConfiguration.protoprotoResponse.proto"<
SignalingGetConfiguration
request (2.proto.Request"©
!SignalingGetConfigurationResponse!
response (2.proto.ResponseF

ice_server (22.proto.SignalingGetConfigurationResponse.IceServer
voice_calling (
video_calling (
screen_sharing (
secret_chat (>
	IceServer
url (	

credential (	
username (	B0
net.iGap.protoBProtoSignalingGetConfigurationbproto3'
        , true);

        static::$is_initialized = true;
    }
}

