<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StoryRoomAddNew.proto

namespace GPBMetadata;

class StoryRoomAddNew
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        \GPBMetadata\StoryUserAddNew::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ô
StoryRoomAddNew.protoprotoResponse.protoGlobal.protoStoryUserAddNew.proto"t
StoryRoomAddNew
request (2.proto.Request
room_id (B0+
token_batch (2.proto.StoryAddRequest"Y
StoryRoomAddNewResponse!
response (2.proto.Response
story (2.proto.StoryB&
net.iGap.protoBProtoStoryRoomAddNewbproto3'
        , true);

        static::$is_initialized = true;
    }
}

