<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StoryUserAddNew.proto

namespace GPBMetadata;

class StoryUserAddNew
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
Û
StoryUserAddNew.protoprotoResponse.protoGlobal.proto"1
StoryAddRequest
token (	
caption (	"_
StoryUserAddNew
request (2.proto.Request+
token_batch (2.proto.StoryAddRequest"Y
StoryUserAddNewResponse!
response (2.proto.Response
story (2.proto.StoryB&
net.iGap.protoBProtoStoryUserAddNewbproto3'
        , true);

        static::$is_initialized = true;
    }
}

