<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserContactsImport.proto

namespace GPBMetadata;

class UserContactsImport
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
ƒ
UserContactsImport.protoprotoResponse.proto"ã
UserContactsImport
request (2.proto.Request3
contacts (2!.proto.UserContactsImport.Contact
force (
contact_hash (	R
Contact
phone (	

first_name (	
	last_name (	
	client_id (	"¶
UserContactsImportResponse!
response (2.proto.ResponseF
registered_contacts (2).proto.UserContactsImportResponse.Contact-
Contact
	client_id (	
user_id (B)
net.iGap.protoBProtoUserContactsImportbproto3'
        , true);

        static::$is_initialized = true;
    }
}

