<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserContactsUnblock.proto

namespace GPBMetadata;

class UserContactsUnblock
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
‚
UserContactsUnblock.protoprotoResponse.proto"G
UserContactsUnblock
request (2.proto.Request
user_id ("Q
UserContactsUnblockResponse!
response (2.proto.Response
user_id (B*
net.iGap.protoBProtoUserContactsUnblockbproto3'
        , true);

        static::$is_initialized = true;
    }
}

