<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserGetDeleteToken.proto

namespace GPBMetadata;

class UserGetDeleteToken
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
Â
UserGetDeleteToken.protoprotoResponse.proto"E
UserGetDeleteToken
request (2.proto.Request
app_id ("”
UserGetDeleteTokenResponse!
response (2.proto.Response
resend_delay (

sms_number (
token_regex (	
token_length (	B)
net.iGap.protoBProtoUserGetDeleteTokenbproto3'
        , true);

        static::$is_initialized = true;
    }
}

