<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserTwoStepVerificationChangeRecoveryEmail.proto

namespace GPBMetadata;

class UserTwoStepVerificationChangeRecoveryEmail
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
€
0UserTwoStepVerificationChangeRecoveryEmail.protoprotoResponse.proto"n
*UserTwoStepVerificationChangeRecoveryEmail
request (2.proto.Request
password (	
email (	"z
2UserTwoStepVerificationChangeRecoveryEmailResponse!
response (2.proto.Response!
unconfirmed_email_pattern (	BA
net.iGap.protoB/ProtoUserTwoStepVerificationChangeRecoveryEmailbproto3'
        , true);

        static::$is_initialized = true;
    }
}

