<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileGetGender.proto

namespace GPBMetadata;

class UserProfileGetGender
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
‘
UserProfileGetGender.protoprotoResponse.protoGlobal.proto"7
UserProfileGetGender
request (2.proto.Request"`
UserProfileGetGenderResponse!
response (2.proto.Response
gender (2.proto.GenderB+
net.iGap.protoBProtoUserProfileGetGenderbproto3'
        , true);

        static::$is_initialized = true;
    }
}

