<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserTwoStepVerificationSetPassword.proto

namespace GPBMetadata;

class UserTwoStepVerificationSetPassword
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
æ
(UserTwoStepVerificationSetPassword.protoprotoResponse.proto"ë
"UserTwoStepVerificationSetPassword
request (2.proto.Request
old_password (	
new_password (	
recovery_email (	
question_one (	

answer_one (	
question_two (	

answer_two (	
hint	 (	"r
*UserTwoStepVerificationSetPasswordResponse!
response (2.proto.Response!
unconfirmed_email_pattern (	B9
net.iGap.protoB\'ProtoUserTwoStepVerificationSetPasswordbproto3'
        , true);

        static::$is_initialized = true;
    }
}

