<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserIVandGetActivities.proto

namespace GPBMetadata;

class UserIVandGetActivities
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ë
UserIVandGetActivities.protoprotoResponse.protoGlobal.proto"`
UserIVandGetActivities
request (2.proto.Request%

pagination (2.proto.Pagination"m
UserIVandGetActivitiesResponse!
response (2.proto.Response(

activities (2.proto.IVandActivityB-
net.iGap.protoBProtoUserIVandGetActivitiesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

