<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileGetBio.proto

namespace GPBMetadata;

class UserProfileGetBio
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
å
UserProfileGetBio.protoprotoResponse.proto"4
UserProfileGetBio
request (2.proto.Request"K
UserProfileGetBioResponse!
response (2.proto.Response
bio (	B(
net.iGap.protoBProtoUserProfileGetBiobproto3'
        , true);

        static::$is_initialized = true;
    }
}

