<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserContactsGetBlockedList.proto

namespace GPBMetadata;

class UserContactsGetBlockedList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
æ
 UserContactsGetBlockedList.protoprotoResponse.proto"=
UserContactsGetBlockedList
request (2.proto.Request"°
"UserContactsGetBlockedListResponse!
response (2.proto.Response<
user (2..proto.UserContactsGetBlockedListResponse.User)
User
user_id (
cache_id (	B1
net.iGap.protoBProtoUserContactsGetBlockedListbproto3'
        , true);

        static::$is_initialized = true;
    }
}

