<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserInfo.proto

namespace GPBMetadata;

class UserInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
ø
UserInfo.protoprotoResponse.protoGlobal.proto"<
UserInfo
request (2.proto.Request
user_id ("Z
UserInfoResponse!
response (2.proto.Response#
user (2.proto.RegisteredUserB
net.iGap.protoBProtoUserInfobproto3'
        , true);

        static::$is_initialized = true;
    }
}

