<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserAvatarGetList.proto

namespace GPBMetadata;

class UserAvatarGetList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
–
UserAvatarGetList.protoprotoResponse.protoGlobal.proto"E
UserAvatarGetList
request (2.proto.Request
user_id ("]
UserAvatarGetListResponse!
response (2.proto.Response
avatar (2.proto.AvatarB(
net.iGap.protoBProtoUserAvatarGetListbproto3'
        , true);

        static::$is_initialized = true;
    }
}

