<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserAvatarAdd.proto

namespace GPBMetadata;

class UserAvatarAdd
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
‰
UserAvatarAdd.protoprotoResponse.protoGlobal.proto"D
UserAvatarAdd
request (2.proto.Request

attachment (	"Y
UserAvatarAddResponse!
response (2.proto.Response
avatar (2.proto.AvatarB$
net.iGap.protoBProtoUserAvatarAddbproto3'
        , true);

        static::$is_initialized = true;
    }
}

