<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileGetNickname.proto

namespace GPBMetadata;

class UserProfileGetNickname
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
þ
UserProfileGetNickname.protoprotoResponse.proto"9
UserProfileGetNickname
request (2.proto.Request"U
UserProfileGetNicknameResponse!
response (2.proto.Response
nickname (	B-
net.iGap.protoBProtoUserProfileGetNicknamebproto3'
        , true);

        static::$is_initialized = true;
    }
}

