<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserSessionLogout.proto

namespace GPBMetadata;

class UserSessionLogout
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ø
UserSessionLogout.protoprotoResponse.proto"4
UserSessionLogout
request (2.proto.Request">
UserSessionLogoutResponse!
response (2.proto.ResponseB(
net.iGap.protoBProtoUserSessionLogoutbproto3'
        , true);

        static::$is_initialized = true;
    }
}

