<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileGetNationalCode.proto

namespace GPBMetadata;

class UserProfileGetNationalCode
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
“
 UserProfileGetNationalCode.protoprotoResponse.proto"=
UserProfileGetNationalCode
request (2.proto.Request"^
"UserProfileGetNationalCodeResponse!
response (2.proto.Response
national_code (	B1
net.iGap.protoBProtoUserProfileGetNationalCodebproto3'
        , true);

        static::$is_initialized = true;
    }
}

