<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserTwoStepVerificationVerifyRecoveryEmail.proto

namespace GPBMetadata;

class UserTwoStepVerificationVerifyRecoveryEmail
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ë
0UserTwoStepVerificationVerifyRecoveryEmail.protoprotoResponse.proto"\\
*UserTwoStepVerificationVerifyRecoveryEmail
request (2.proto.Request
token (	"W
2UserTwoStepVerificationVerifyRecoveryEmailResponse!
response (2.proto.ResponseBA
net.iGap.protoB/ProtoUserTwoStepVerificationVerifyRecoveryEmailbproto3'
        , true);

        static::$is_initialized = true;
    }
}

