<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserSetBot.proto

namespace GPBMetadata;

class UserSetBot
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ü
UserSetBot.protoprotoResponse.proto"=

UserSetBot
request (2.proto.Request
status ("G
UserSetBotResponse!
response (2.proto.Response
status (B!
net.iGap.protoBProtoUserSetBotbproto3'
        , true);

        static::$is_initialized = true;
    }
}

