<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WalletPaymentInit.proto

namespace GPBMetadata;

class WalletPaymentInit
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(
            '
Û
WalletPaymentInit.protoprotoResponse.protoGlobal.proto"ù
WalletPaymentInit
request (2.proto.Request!
language (2.proto.Language
jwt (	

to_user_id (
amount (
description (	"a
WalletPaymentInitResponse!
response (2.proto.Response
token (	

public_key (	B(
net.iGap.protoBProtoWalletPaymentInitbproto3'
        , true);

        static::$is_initialized = true;
    }
}

