<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WalletIdMapping.proto

namespace GPBMetadata;

class WalletIdMapping
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
ô
WalletIdMapping.protoprotoResponse.proto"E
WalletIdMapping
request (2.proto.Request
	wallet_id (	"M
WalletIdMappingResponse!
response (2.proto.Response
user_id (B&
net.iGap.protoBProtoWalletIdMappingbproto3'
        , true);

        static::$is_initialized = true;
    }
}

