<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WalletRegister.proto

namespace GPBMetadata;

class WalletRegister
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ì
WalletRegister.protoprotoResponse.proto"1
WalletRegister
request (2.proto.Request";
WalletRegisterResponse!
response (2.proto.ResponseB%
net.iGap.protoBProtoWalletRegisterbproto3'
        , true);

        static::$is_initialized = true;
    }
}

