<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto\MplSale;

use UnexpectedValueException;

/**
 * Protobuf type <code>proto.MplSale.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>PENDING_VERIFY = 0;</code>
     */
    const PENDING_VERIFY = 0;
    /**
     * Generated from protobuf enum <code>SUCCESS = 1;</code>
     */
    const SUCCESS = 1;
    /**
     * Generated from protobuf enum <code>FAILED = 2;</code>
     */
    const FAILED = 2;
    /**
     * Generated from protobuf enum <code>REVERSED = 3;</code>
     */
    const REVERSED = 3;

    private static $valueToName = [
        self::PENDING_VERIFY => 'PENDING_VERIFY',
        self::SUCCESS => 'SUCCESS',
        self::FAILED => 'FAILED',
        self::REVERSED => 'REVERSED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Status::class, \Proto\MplSale_Status::class);

