<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientResolveUsername.proto

namespace Proto\ClientResolveUsernameResponse;

use UnexpectedValueException;

/**
 * Protobuf type <code>proto.ClientResolveUsernameResponse.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>USER = 0;</code>
     */
    const USER = 0;
    /**
     * Generated from protobuf enum <code>ROOM = 1;</code>
     */
    const ROOM = 1;

    private static $valueToName = [
        self::USER => 'USER',
        self::ROOM => 'ROOM',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Proto\ClientResolveUsernameResponse_Type::class);

