<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupAddAdmin.proto

namespace Proto\GroupAddAdmin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.GroupAddAdmin.AdminRights</code>
 */
class AdminRights extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool modify_room = 1;</code>
     */
    protected $modify_room = false;
    /**
     * Generated from protobuf field <code>bool delete_message = 2;</code>
     */
    protected $delete_message = false;
    /**
     * Generated from protobuf field <code>bool pin_message = 3;</code>
     */
    protected $pin_message = false;
    /**
     * Generated from protobuf field <code>bool add_member = 4;</code>
     */
    protected $add_member = false;
    /**
     * Generated from protobuf field <code>bool ban_member = 5;</code>
     */
    protected $ban_member = false;
    /**
     * Generated from protobuf field <code>bool get_member = 6;</code>
     */
    protected $get_member = false;
    /**
     * Generated from protobuf field <code>bool add_admin = 7;</code>
     */
    protected $add_admin = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $modify_room
     *     @type bool $delete_message
     *     @type bool $pin_message
     *     @type bool $add_member
     *     @type bool $ban_member
     *     @type bool $get_member
     *     @type bool $add_admin
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GroupAddAdmin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool modify_room = 1;</code>
     * @return bool
     */
    public function getModifyRoom()
    {
        return $this->modify_room;
    }

    /**
     * Generated from protobuf field <code>bool modify_room = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setModifyRoom($var)
    {
        GPBUtil::checkBool($var);
        $this->modify_room = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool delete_message = 2;</code>
     * @return bool
     */
    public function getDeleteMessage()
    {
        return $this->delete_message;
    }

    /**
     * Generated from protobuf field <code>bool delete_message = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeleteMessage($var)
    {
        GPBUtil::checkBool($var);
        $this->delete_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool pin_message = 3;</code>
     * @return bool
     */
    public function getPinMessage()
    {
        return $this->pin_message;
    }

    /**
     * Generated from protobuf field <code>bool pin_message = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setPinMessage($var)
    {
        GPBUtil::checkBool($var);
        $this->pin_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool add_member = 4;</code>
     * @return bool
     */
    public function getAddMember()
    {
        return $this->add_member;
    }

    /**
     * Generated from protobuf field <code>bool add_member = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setAddMember($var)
    {
        GPBUtil::checkBool($var);
        $this->add_member = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ban_member = 5;</code>
     * @return bool
     */
    public function getBanMember()
    {
        return $this->ban_member;
    }

    /**
     * Generated from protobuf field <code>bool ban_member = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setBanMember($var)
    {
        GPBUtil::checkBool($var);
        $this->ban_member = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool get_member = 6;</code>
     * @return bool
     */
    public function getGetMember()
    {
        return $this->get_member;
    }

    /**
     * Generated from protobuf field <code>bool get_member = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setGetMember($var)
    {
        GPBUtil::checkBool($var);
        $this->get_member = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool add_admin = 7;</code>
     * @return bool
     */
    public function getAddAdmin()
    {
        return $this->add_admin;
    }

    /**
     * Generated from protobuf field <code>bool add_admin = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setAddAdmin($var)
    {
        GPBUtil::checkBool($var);
        $this->add_admin = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AdminRights::class, \Proto\GroupAddAdmin_AdminRights::class);

