<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: access_date_time.proto

namespace App\Core\Grpc\Models;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ir.kalabazzar.proto.AccessSettingTime</code>
 */
class AccessSettingTime extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>uint64 access_setting_id = 2;</code>
     */
    protected $access_setting_id = 0;
    /**
     * Generated from protobuf field <code>string start_at = 3;</code>
     */
    protected $start_at = '';
    /**
     * Generated from protobuf field <code>string end_at = 4;</code>
     */
    protected $end_at = '';
    /**
     * Generated from protobuf field <code>string created_at = 7;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 8;</code>
     */
    protected $updated_at = '';
    /**
     * Generated from protobuf field <code>optional string deleted_at = 9;</code>
     */
    protected $deleted_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type int|string $id
     * @type int|string $access_setting_id
     * @type string $start_at
     * @type string $end_at
     * @type string $created_at
     * @type string $updated_at
     * @type string $deleted_at
     * }
     */
    public function __construct($data = NULL)
    {
        \App\Core\Grpc\GPBMetadata\AccessDateTime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 access_setting_id = 2;</code>
     * @return int|string
     */
    public function getAccessSettingId()
    {
        return $this->access_setting_id;
    }

    /**
     * Generated from protobuf field <code>uint64 access_setting_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAccessSettingId($var)
    {
        GPBUtil::checkUint64($var);
        $this->access_setting_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string start_at = 3;</code>
     * @return string
     */
    public function getStartAt()
    {
        return $this->start_at;
    }

    /**
     * Generated from protobuf field <code>string start_at = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStartAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string end_at = 4;</code>
     * @return string
     */
    public function getEndAt()
    {
        return $this->end_at;
    }

    /**
     * Generated from protobuf field <code>string end_at = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEndAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 7;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 8;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string deleted_at = 9;</code>
     * @return string
     */
    public function getDeletedAt()
    {
        return isset($this->deleted_at) ? $this->deleted_at : '';
    }

    /**
     * Generated from protobuf field <code>optional string deleted_at = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDeletedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->deleted_at = $var;

        return $this;
    }

    public function hasDeletedAt()
    {
        return isset($this->deleted_at);
    }

    public function clearDeletedAt()
    {
        unset($this->deleted_at);
    }

}

