<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_request.proto

namespace App\Core\Grpc\Models;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * request
 *
 * Generated from protobuf message <code>ir.kalabazzar.proto.CreatePermissionRequestRequest</code>
 */
class CreatePermissionRequestRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 user_id = 2;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>string permission_id = 5;</code>
     */
    protected $permission_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type int|string $user_id
     * @type string $permission_id
     * }
     */
    public function __construct($data = NULL)
    {
        \App\Core\Grpc\GPBMetadata\PermissionRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 2;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string permission_id = 5;</code>
     * @return string
     */
    public function getPermissionId()
    {
        return $this->permission_id;
    }

    /**
     * Generated from protobuf field <code>string permission_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPermissionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->permission_id = $var;

        return $this;
    }

}

