<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdui.proto

namespace App\Core\Grpc\Models;

use Google\Protobuf\Internal\GPBUtil;

/**
 * request
 *
 * Generated from protobuf message <code>ir.kalabazzar.proto.GetSduiRequest</code>
 */
class GetSduiRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.SduiType type = 2;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.SduiProject project = 3;</code>
     */
    protected $project = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type string $path
     * @type int $type
     * @type int $project
     * }
     */
    public function __construct($data = NULL)
    {
        \App\Core\Grpc\GPBMetadata\Sdui::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.SduiType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.SduiType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \App\Core\Grpc\Models\SduiType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.SduiProject project = 3;</code>
     * @return int
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.SduiProject project = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setProject($var)
    {
        GPBUtil::checkEnum($var, \App\Core\Grpc\Models\SduiProject::class);
        $this->project = $var;

        return $this;
    }

}

