<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_access_setting.proto

namespace App\Core\Grpc\Models;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ir.kalabazzar.proto.IndexUserAccessSettingData</code>
 */
class IndexUserAccessSettingData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.UserAccessSetting user_access_settings = 1;</code>
     */
    private $user_access_settings;
    /**
     * Generated from protobuf field <code>uint32 total_count = 2;</code>
     */
    protected $total_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type array<\App\Core\Grpc\Models\UserAccessSetting>|\Google\Protobuf\Internal\RepeatedField $user_access_settings
     * @type int $total_count
     * }
     */
    public function __construct($data = NULL)
    {
        \App\Core\Grpc\GPBMetadata\UserAccessSetting::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.UserAccessSetting user_access_settings = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserAccessSettings()
    {
        return $this->user_access_settings;
    }

    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.UserAccessSetting user_access_settings = 1;</code>
     * @param array<\App\Core\Grpc\Models\UserAccessSetting>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserAccessSettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Core\Grpc\Models\UserAccessSetting::class);
        $this->user_access_settings = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 total_count = 2;</code>
     * @return int
     */
    public function getTotalCount()
    {
        return $this->total_count;
    }

    /**
     * Generated from protobuf field <code>uint32 total_count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->total_count = $var;

        return $this;
    }

}

