<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apikey.proto

namespace App\Core\Grpc\Models;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ir.kalabazzar.proto.IndexApiKeyData</code>
 */
class IndexApiKeyData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 total_count = 2;</code>
     */
    protected $total_count = 0;
    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.ApiKey api_keys = 1;</code>
     */
    private $api_keys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type array<\App\Core\Grpc\Models\ApiKey>|\Google\Protobuf\Internal\RepeatedField $api_keys
     * @type int $total_count
     * }
     */
    public function __construct($data = NULL)
    {
        \App\Core\Grpc\GPBMetadata\Apikey::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.ApiKey api_keys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getApiKeys()
    {
        return $this->api_keys;
    }

    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.ApiKey api_keys = 1;</code>
     * @param array<\App\Core\Grpc\Models\ApiKey>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setApiKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Core\Grpc\Models\ApiKey::class);
        $this->api_keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 total_count = 2;</code>
     * @return int
     */
    public function getTotalCount()
    {
        return $this->total_count;
    }

    /**
     * Generated from protobuf field <code>uint32 total_count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->total_count = $var;

        return $this;
    }

}

