<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: role.proto

namespace App\Core\Grpc\Models;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ir.kalabazzar.proto.IndexRoleData</code>
 */
class IndexRoleData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 total_count = 2;</code>
     */
    protected $total_count = 0;
    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.Role roles = 1;</code>
     */
    private $roles;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type array<\App\Core\Grpc\Models\Role>|\Google\Protobuf\Internal\RepeatedField $roles
     * @type int $total_count
     * }
     */
    public function __construct($data = NULL)
    {
        \App\Core\Grpc\GPBMetadata\Role::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.Role roles = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.Role roles = 1;</code>
     * @param array<\App\Core\Grpc\Models\Role>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Core\Grpc\Models\Role::class);
        $this->roles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 total_count = 2;</code>
     * @return int
     */
    public function getTotalCount()
    {
        return $this->total_count;
    }

    /**
     * Generated from protobuf field <code>uint32 total_count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->total_count = $var;

        return $this;
    }

}

