<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission.proto

namespace App\Core\Grpc\Models;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ir.kalabazzar.proto.IndexSubModuleData</code>
 */
class IndexSubModuleData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.Permission Permissions = 1;</code>
     */
    private $Permissions;
    /**
     * Generated from protobuf field <code>uint32 total_count = 2;</code>
     */
    protected $total_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type array<\App\Core\Grpc\Models\Permission>|\Google\Protobuf\Internal\RepeatedField $Permissions
     * @type int $total_count
     * }
     */
    public function __construct($data = NULL)
    {
        \App\Core\Grpc\GPBMetadata\Permission::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.Permission Permissions = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPermissions()
    {
        return $this->Permissions;
    }

    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.Permission Permissions = 1;</code>
     * @param array<\App\Core\Grpc\Models\Permission>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPermissions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Core\Grpc\Models\Permission::class);
        $this->Permissions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 total_count = 2;</code>
     * @return int
     */
    public function getTotalCount()
    {
        return $this->total_count;
    }

    /**
     * Generated from protobuf field <code>uint32 total_count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->total_count = $var;

        return $this;
    }

}

