<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum.proto

namespace App\Core\Grpc\Models;

use UnexpectedValueException;

/**
 * Protobuf type <code>ir.kalabazzar.proto.LocationType</code>
 */
class LocationType
{
    /**
     * Generated from protobuf enum <code>ANY_WHERE = 0;</code>
     */
    const ANY_WHERE = 0;
    /**
     * Generated from protobuf enum <code>IN_ORGANIZATION = 1;</code>
     */
    const IN_ORGANIZATION = 1;

    private static $valueToName = [
        self::ANY_WHERE => 'ANY_WHERE',
        self::IN_ORGANIZATION => 'IN_ORGANIZATION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

