<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: module_group.proto

namespace App\Core\Grpc\Models;

use Google\Protobuf\Internal\GPBUtil;

/**
 * model
 *
 * Generated from protobuf message <code>ir.kalabazzar.proto.ModuleGroup</code>
 */
class ModuleGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string fa_name = 2;</code>
     */
    protected $fa_name = '';
    /**
     * Generated from protobuf field <code>string en_name = 3;</code>
     */
    protected $en_name = '';
    /**
     * Generated from protobuf field <code>optional uint64 parent_id = 4;</code>
     */
    protected $parent_id = null;
    /**
     * Generated from protobuf field <code>optional .ir.kalabazzar.proto.ModuleGroup parent = 5;</code>
     */
    protected $parent = null;
    /**
     * Generated from protobuf field <code>int64 priority = 6;</code>
     */
    protected $priority = 0;
    /**
     * Generated from protobuf field <code>string created_at = 7;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 8;</code>
     */
    protected $updated_at = '';
    /**
     * Generated from protobuf field <code>optional string deleted_at = 9;</code>
     */
    protected $deleted_at = null;
    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.Module modules = 10;</code>
     */
    private $modules;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type int|string $id
     * @type string $fa_name
     * @type string $en_name
     * @type int|string $parent_id
     * @type \App\Core\Grpc\Models\ModuleGroup $parent
     * @type int|string $priority
     * @type string $created_at
     * @type string $updated_at
     * @type string $deleted_at
     * @type array<\App\Core\Grpc\Models\Module>|\Google\Protobuf\Internal\RepeatedField $modules
     * }
     */
    public function __construct($data = NULL)
    {
        \App\Core\Grpc\GPBMetadata\ModuleGroup::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fa_name = 2;</code>
     * @return string
     */
    public function getFaName()
    {
        return $this->fa_name;
    }

    /**
     * Generated from protobuf field <code>string fa_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFaName($var)
    {
        GPBUtil::checkString($var, True);
        $this->fa_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string en_name = 3;</code>
     * @return string
     */
    public function getEnName()
    {
        return $this->en_name;
    }

    /**
     * Generated from protobuf field <code>string en_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEnName($var)
    {
        GPBUtil::checkString($var, True);
        $this->en_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint64 parent_id = 4;</code>
     * @return int|string
     */
    public function getParentId()
    {
        return isset($this->parent_id) ? $this->parent_id : 0;
    }

    /**
     * Generated from protobuf field <code>optional uint64 parent_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setParentId($var)
    {
        GPBUtil::checkUint64($var);
        $this->parent_id = $var;

        return $this;
    }

    public function hasParentId()
    {
        return isset($this->parent_id);
    }

    public function clearParentId()
    {
        unset($this->parent_id);
    }

    /**
     * Generated from protobuf field <code>optional .ir.kalabazzar.proto.ModuleGroup parent = 5;</code>
     * @return \App\Core\Grpc\Models\ModuleGroup|null
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Generated from protobuf field <code>optional .ir.kalabazzar.proto.ModuleGroup parent = 5;</code>
     * @param \App\Core\Grpc\Models\ModuleGroup $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkMessage($var, \App\Core\Grpc\Models\ModuleGroup::class);
        $this->parent = $var;

        return $this;
    }

    public function hasParent()
    {
        return isset($this->parent);
    }

    public function clearParent()
    {
        unset($this->parent);
    }

    /**
     * Generated from protobuf field <code>int64 priority = 6;</code>
     * @return int|string
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * Generated from protobuf field <code>int64 priority = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPriority($var)
    {
        GPBUtil::checkInt64($var);
        $this->priority = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 7;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 8;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string deleted_at = 9;</code>
     * @return string
     */
    public function getDeletedAt()
    {
        return isset($this->deleted_at) ? $this->deleted_at : '';
    }

    /**
     * Generated from protobuf field <code>optional string deleted_at = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDeletedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->deleted_at = $var;

        return $this;
    }

    public function hasDeletedAt()
    {
        return isset($this->deleted_at);
    }

    public function clearDeletedAt()
    {
        unset($this->deleted_at);
    }

    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.Module modules = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getModules()
    {
        return $this->modules;
    }

    /**
     * Generated from protobuf field <code>repeated .ir.kalabazzar.proto.Module modules = 10;</code>
     * @param array<\App\Core\Grpc\Models\Module>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setModules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Core\Grpc\Models\Module::class);
        $this->modules = $arr;

        return $this;
    }

}

