<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum.proto

namespace App\Core\Grpc\Models;

use UnexpectedValueException;

/**
 * enum
 *
 * Protobuf type <code>ir.kalabazzar.proto.SensitivityLevel</code>
 */
class SensitivityLevel
{
    /**
     * Generated from protobuf enum <code>NORMAL = 0;</code>
     */
    const NORMAL = 0;
    /**
     * Generated from protobuf enum <code>CONFIDENTIAL = 1;</code>
     */
    const CONFIDENTIAL = 1;
    /**
     * Generated from protobuf enum <code>VERY_CONFIDENTIAL = 2;</code>
     */
    const VERY_CONFIDENTIAL = 2;

    private static $valueToName = [
        self::NORMAL => 'NORMAL',
        self::CONFIDENTIAL => 'CONFIDENTIAL',
        self::VERY_CONFIDENTIAL => 'VERY_CONFIDENTIAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

