<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_access_setting.proto

namespace App\Core\Grpc\Models;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ir.kalabazzar.proto.UpdateUserAccessSettingRequest</code>
 */
class UpdateUserAccessSettingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.UserLevel user_level = 2;</code>
     */
    protected $user_level = 0;
    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.AccessSettingTime access_setting_time = 3;</code>
     */
    protected $access_setting_time = null;
    /**
     * Generated from protobuf field <code>optional .ir.kalabazzar.proto.AccessSettingDate access_setting_date = 4;</code>
     */
    protected $access_setting_date = null;
    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.LocationType location_type = 5;</code>
     */
    protected $location_type = 0;
    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.TokenType token_type = 6;</code>
     */
    protected $token_type = 0;
    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.DeviceType device_type = 7;</code>
     */
    protected $device_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type int|string $id
     * @type int $user_level
     * @type \App\Core\Grpc\Models\AccessSettingTime $access_setting_time
     * @type \App\Core\Grpc\Models\AccessSettingDate $access_setting_date
     * @type int $location_type
     * @type int $token_type
     * @type int $device_type
     * }
     */
    public function __construct($data = NULL)
    {
        \App\Core\Grpc\GPBMetadata\UserAccessSetting::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.UserLevel user_level = 2;</code>
     * @return int
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.UserLevel user_level = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkEnum($var, \App\Core\Grpc\Models\UserLevel::class);
        $this->user_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.AccessSettingTime access_setting_time = 3;</code>
     * @return \App\Core\Grpc\Models\AccessSettingTime|null
     */
    public function getAccessSettingTime()
    {
        return $this->access_setting_time;
    }

    public function hasAccessSettingTime()
    {
        return isset($this->access_setting_time);
    }

    public function clearAccessSettingTime()
    {
        unset($this->access_setting_time);
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.AccessSettingTime access_setting_time = 3;</code>
     * @param \App\Core\Grpc\Models\AccessSettingTime $var
     * @return $this
     */
    public function setAccessSettingTime($var)
    {
        GPBUtil::checkMessage($var, \App\Core\Grpc\Models\AccessSettingTime::class);
        $this->access_setting_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .ir.kalabazzar.proto.AccessSettingDate access_setting_date = 4;</code>
     * @return \App\Core\Grpc\Models\AccessSettingDate|null
     */
    public function getAccessSettingDate()
    {
        return $this->access_setting_date;
    }

    public function hasAccessSettingDate()
    {
        return isset($this->access_setting_date);
    }

    public function clearAccessSettingDate()
    {
        unset($this->access_setting_date);
    }

    /**
     * Generated from protobuf field <code>optional .ir.kalabazzar.proto.AccessSettingDate access_setting_date = 4;</code>
     * @param \App\Core\Grpc\Models\AccessSettingDate $var
     * @return $this
     */
    public function setAccessSettingDate($var)
    {
        GPBUtil::checkMessage($var, \App\Core\Grpc\Models\AccessSettingDate::class);
        $this->access_setting_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.LocationType location_type = 5;</code>
     * @return int
     */
    public function getLocationType()
    {
        return $this->location_type;
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.LocationType location_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLocationType($var)
    {
        GPBUtil::checkEnum($var, \App\Core\Grpc\Models\LocationType::class);
        $this->location_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.TokenType token_type = 6;</code>
     * @return int
     */
    public function getTokenType()
    {
        return $this->token_type;
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.TokenType token_type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setTokenType($var)
    {
        GPBUtil::checkEnum($var, \App\Core\Grpc\Models\TokenType::class);
        $this->token_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.DeviceType device_type = 7;</code>
     * @return int
     */
    public function getDeviceType()
    {
        return $this->device_type;
    }

    /**
     * Generated from protobuf field <code>.ir.kalabazzar.proto.DeviceType device_type = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setDeviceType($var)
    {
        GPBUtil::checkEnum($var, \App\Core\Grpc\Models\DeviceType::class);
        $this->device_type = $var;

        return $this;
    }

}

