<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum.proto

namespace App\Core\Grpc\Models;

use UnexpectedValueException;

/**
 * Protobuf type <code>ir.kalabazzar.proto.UserLevel</code>
 */
class UserLevel
{
    /**
     * Generated from protobuf enum <code>SUPER_ADMIN = 0;</code>
     */
    const SUPER_ADMIN = 0;
    /**
     * Generated from protobuf enum <code>SENIOR_MANAGER = 1;</code>
     */
    const SENIOR_MANAGER = 1;
    /**
     * Generated from protobuf enum <code>MIDDLE_MANAGER = 2;</code>
     */
    const MIDDLE_MANAGER = 2;
    /**
     * Generated from protobuf enum <code>JUNIOR_STAFF = 3;</code>
     */
    const JUNIOR_STAFF = 3;

    private static $valueToName = [
        self::SUPER_ADMIN => 'SUPER_ADMIN',
        self::SENIOR_MANAGER => 'SENIOR_MANAGER',
        self::MIDDLE_MANAGER => 'MIDDLE_MANAGER',
        self::JUNIOR_STAFF => 'JUNIOR_STAFF',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

