<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace App\Core\Grpc\Models;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ir.kalabazzar.proto.UserLoginData</code>
 */
class UserLoginData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .ir.kalabazzar.proto.User user = 1;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>optional string token = 2;</code>
     */
    protected $token = null;
    /**
     * Generated from protobuf field <code>optional string refresh_token = 3;</code>
     */
    protected $refresh_token = null;
    /**
     * Generated from protobuf field <code>optional string username = 4;</code>
     */
    protected $username = null;
    /**
     * Generated from protobuf field <code>repeated string active_2fa = 5;</code>
     */
    private $active_2fa;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type \App\Core\Grpc\Models\User $user
     * @type string $token
     * @type string $refresh_token
     * @type string $username
     * @type array<string>|\Google\Protobuf\Internal\RepeatedField $active_2fa
     * }
     */
    public function __construct($data = NULL)
    {
        \App\Core\Grpc\GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .ir.kalabazzar.proto.User user = 1;</code>
     * @return \App\Core\Grpc\Models\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>optional .ir.kalabazzar.proto.User user = 1;</code>
     * @param \App\Core\Grpc\Models\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \App\Core\Grpc\Models\User::class);
        $this->user = $var;

        return $this;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>optional string token = 2;</code>
     * @return string
     */
    public function getToken()
    {
        return isset($this->token) ? $this->token : '';
    }

    /**
     * Generated from protobuf field <code>optional string token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    public function hasToken()
    {
        return isset($this->token);
    }

    public function clearToken()
    {
        unset($this->token);
    }

    /**
     * Generated from protobuf field <code>optional string refresh_token = 3;</code>
     * @return string
     */
    public function getRefreshToken()
    {
        return isset($this->refresh_token) ? $this->refresh_token : '';
    }

    /**
     * Generated from protobuf field <code>optional string refresh_token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->refresh_token = $var;

        return $this;
    }

    public function hasRefreshToken()
    {
        return isset($this->refresh_token);
    }

    public function clearRefreshToken()
    {
        unset($this->refresh_token);
    }

    /**
     * Generated from protobuf field <code>optional string username = 4;</code>
     * @return string
     */
    public function getUsername()
    {
        return isset($this->username) ? $this->username : '';
    }

    /**
     * Generated from protobuf field <code>optional string username = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    public function hasUsername()
    {
        return isset($this->username);
    }

    public function clearUsername()
    {
        unset($this->username);
    }

    /**
     * Generated from protobuf field <code>repeated string active_2fa = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActive2Fa()
    {
        return $this->active_2fa;
    }

    /**
     * Generated from protobuf field <code>repeated string active_2fa = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActive2Fa($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->active_2fa = $arr;

        return $this;
    }

}

