<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ChatRoom</code>
 */
class ChatRoom extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.RegisteredUser peer = 1;</code>
     */
    protected $peer = null;
    /**
     * Generated from protobuf field <code>.proto.BotInfo botInfo = 2;</code>
     */
    protected $botInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\RegisteredUser $peer
     *     @type \Proto\BotInfo $botInfo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBGlobal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.RegisteredUser peer = 1;</code>
     * @return \Proto\RegisteredUser|null
     */
    public function getPeer()
    {
        return $this->peer;
    }

    public function hasPeer()
    {
        return isset($this->peer);
    }

    public function clearPeer()
    {
        unset($this->peer);
    }

    /**
     * Generated from protobuf field <code>.proto.RegisteredUser peer = 1;</code>
     * @param \Proto\RegisteredUser $var
     * @return $this
     */
    public function setPeer($var)
    {
        GPBUtil::checkMessage($var, \Proto\RegisteredUser::class);
        $this->peer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.BotInfo botInfo = 2;</code>
     * @return \Proto\BotInfo|null
     */
    public function getBotInfo()
    {
        return $this->botInfo;
    }

    public function hasBotInfo()
    {
        return isset($this->botInfo);
    }

    public function clearBotInfo()
    {
        unset($this->botInfo);
    }

    /**
     * Generated from protobuf field <code>.proto.BotInfo botInfo = 2;</code>
     * @param \Proto\BotInfo $var
     * @return $this
     */
    public function setBotInfo($var)
    {
        GPBUtil::checkMessage($var, \Proto\BotInfo::class);
        $this->botInfo = $var;

        return $this;
    }

}

