<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatClearMessage.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ChatClearMessageResponse</code>
 */
class ChatClearMessageResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    protected $response = null;
    /**
     * Generated from protobuf field <code>uint64 room_id = 2;</code>
     */
    protected $room_id = 0;
    /**
     * Generated from protobuf field <code>uint64 clear_message_id = 3;</code>
     */
    protected $clear_message_id = 0;
    /**
     * Generated from protobuf field <code>uint64 clear_document_id = 4;</code>
     */
    protected $clear_document_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type int|string $room_id
     *     @type int|string $clear_message_id
     *     @type int|string $clear_document_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ChatClearMessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response|null
     */
    public function getResponse()
    {
        return $this->response;
    }

    public function hasResponse()
    {
        return isset($this->response);
    }

    public function clearResponse()
    {
        unset($this->response);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 room_id = 2;</code>
     * @return int|string
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * Generated from protobuf field <code>uint64 room_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkUint64($var);
        $this->room_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 clear_message_id = 3;</code>
     * @return int|string
     */
    public function getClearMessageId()
    {
        return $this->clear_message_id;
    }

    /**
     * Generated from protobuf field <code>uint64 clear_message_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClearMessageId($var)
    {
        GPBUtil::checkUint64($var);
        $this->clear_message_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 clear_document_id = 4;</code>
     * @return int|string
     */
    public function getClearDocumentId()
    {
        return $this->clear_document_id;
    }

    /**
     * Generated from protobuf field <code>uint64 clear_document_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClearDocumentId($var)
    {
        GPBUtil::checkUint64($var);
        $this->clear_document_id = $var;

        return $this;
    }

}

