<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>proto.ClientAction</code>
 */
class ClientAction
{
    /**
     * Generated from protobuf enum <code>CANCEL = 0;</code>
     */
    const CANCEL = 0;
    /**
     * Generated from protobuf enum <code>TYPING = 1;</code>
     */
    const TYPING = 1;
    /**
     * Generated from protobuf enum <code>SENDING_IMAGE = 2;</code>
     */
    const SENDING_IMAGE = 2;
    /**
     * Generated from protobuf enum <code>CAPTURING_IMAGE = 3;</code>
     */
    const CAPTURING_IMAGE = 3;
    /**
     * Generated from protobuf enum <code>SENDING_VIDEO = 4;</code>
     */
    const SENDING_VIDEO = 4;
    /**
     * Generated from protobuf enum <code>CAPTURING_VIDEO = 5;</code>
     */
    const CAPTURING_VIDEO = 5;
    /**
     * Generated from protobuf enum <code>SENDING_AUDIO = 6;</code>
     */
    const SENDING_AUDIO = 6;
    /**
     * Generated from protobuf enum <code>RECORDING_VOICE = 7;</code>
     */
    const RECORDING_VOICE = 7;
    /**
     * Generated from protobuf enum <code>SENDING_VOICE = 8;</code>
     */
    const SENDING_VOICE = 8;
    /**
     * Generated from protobuf enum <code>SENDING_DOCUMENT = 9;</code>
     */
    const SENDING_DOCUMENT = 9;
    /**
     * Generated from protobuf enum <code>SENDING_GIF = 10;</code>
     */
    const SENDING_GIF = 10;
    /**
     * Generated from protobuf enum <code>SENDING_FILE = 11;</code>
     */
    const SENDING_FILE = 11;
    /**
     * Generated from protobuf enum <code>SENDING_LOCATION = 12;</code>
     */
    const SENDING_LOCATION = 12;
    /**
     * Generated from protobuf enum <code>CHOOSING_CONTACT = 13;</code>
     */
    const CHOOSING_CONTACT = 13;
    /**
     * Generated from protobuf enum <code>PAINTING = 14;</code>
     */
    const PAINTING = 14;

    private static $valueToName = [
        self::CANCEL => 'CANCEL',
        self::TYPING => 'TYPING',
        self::SENDING_IMAGE => 'SENDING_IMAGE',
        self::CAPTURING_IMAGE => 'CAPTURING_IMAGE',
        self::SENDING_VIDEO => 'SENDING_VIDEO',
        self::CAPTURING_VIDEO => 'CAPTURING_VIDEO',
        self::SENDING_AUDIO => 'SENDING_AUDIO',
        self::RECORDING_VOICE => 'RECORDING_VOICE',
        self::SENDING_VOICE => 'SENDING_VOICE',
        self::SENDING_DOCUMENT => 'SENDING_DOCUMENT',
        self::SENDING_GIF => 'SENDING_GIF',
        self::SENDING_FILE => 'SENDING_FILE',
        self::SENDING_LOCATION => 'SENDING_LOCATION',
        self::CHOOSING_CONTACT => 'CHOOSING_CONTACT',
        self::PAINTING => 'PAINTING',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

