<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Favorite</code>
 */
class Favorite extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string textcolor = 2;</code>
     */
    protected $textcolor = '';
    /**
     * Generated from protobuf field <code>string bgcolor = 3;</code>
     */
    protected $bgcolor = '';
    /**
     * Generated from protobuf field <code>string value = 4;</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>string image = 5;</code>
     */
    protected $image = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $textcolor
     *     @type string $bgcolor
     *     @type string $value
     *     @type string $image
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBGlobal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string textcolor = 2;</code>
     * @return string
     */
    public function getTextcolor()
    {
        return $this->textcolor;
    }

    /**
     * Generated from protobuf field <code>string textcolor = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTextcolor($var)
    {
        GPBUtil::checkString($var, True);
        $this->textcolor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bgcolor = 3;</code>
     * @return string
     */
    public function getBgcolor()
    {
        return $this->bgcolor;
    }

    /**
     * Generated from protobuf field <code>string bgcolor = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBgcolor($var)
    {
        GPBUtil::checkString($var, True);
        $this->bgcolor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 4;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string image = 5;</code>
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Generated from protobuf field <code>string image = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->image = $var;

        return $this;
    }

}

