<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FileInfo.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.FileInfoResponse</code>
 */
class FileInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    protected $response = null;
    /**
     * Generated from protobuf field <code>.proto.File file = 2;</code>
     */
    protected $file = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type \Proto\File $file
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\FileInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response|null
     */
    public function getResponse()
    {
        return $this->response;
    }

    public function hasResponse()
    {
        return isset($this->response);
    }

    public function clearResponse()
    {
        unset($this->response);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.File file = 2;</code>
     * @return \Proto\File|null
     */
    public function getFile()
    {
        return $this->file;
    }

    public function hasFile()
    {
        return isset($this->file);
    }

    public function clearFile()
    {
        unset($this->file);
    }

    /**
     * Generated from protobuf field <code>.proto.File file = 2;</code>
     * @param \Proto\File $var
     * @return $this
     */
    public function setFile($var)
    {
        GPBUtil::checkMessage($var, \Proto\File::class);
        $this->file = $var;

        return $this;
    }

}

