<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StoryGetStories.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.GroupedStories</code>
 */
class GroupedStories extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.GroupedStories.Originator originator = 1;</code>
     */
    protected $originator = 0;
    /**
     * Generated from protobuf field <code>uint64 originator_id = 2 [jstype = JS_STRING];</code>
     */
    protected $originator_id = 0;
    /**
     * Generated from protobuf field <code>string originator_name = 3;</code>
     */
    protected $originator_name = '';
    /**
     * Generated from protobuf field <code>bool seen_all_group_stories = 4;</code>
     */
    protected $seen_all_group_stories = false;
    /**
     * Generated from protobuf field <code>repeated .proto.Story stories = 5;</code>
     */
    private $stories;
    /**
     * Generated from protobuf field <code>bool self = 6;</code>
     */
    protected $self = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $originator
     *     @type int|string $originator_id
     *     @type string $originator_name
     *     @type bool $seen_all_group_stories
     *     @type array<\Proto\Story>|\Google\Protobuf\Internal\RepeatedField $stories
     *     @type bool $self
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StoryGetStories::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.GroupedStories.Originator originator = 1;</code>
     * @return int
     */
    public function getOriginator()
    {
        return $this->originator;
    }

    /**
     * Generated from protobuf field <code>.proto.GroupedStories.Originator originator = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOriginator($var)
    {
        GPBUtil::checkEnum($var, \Proto\GroupedStories\Originator::class);
        $this->originator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 originator_id = 2 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getOriginatorId()
    {
        return $this->originator_id;
    }

    /**
     * Generated from protobuf field <code>uint64 originator_id = 2 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setOriginatorId($var)
    {
        GPBUtil::checkUint64($var);
        $this->originator_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string originator_name = 3;</code>
     * @return string
     */
    public function getOriginatorName()
    {
        return $this->originator_name;
    }

    /**
     * Generated from protobuf field <code>string originator_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginatorName($var)
    {
        GPBUtil::checkString($var, True);
        $this->originator_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool seen_all_group_stories = 4;</code>
     * @return bool
     */
    public function getSeenAllGroupStories()
    {
        return $this->seen_all_group_stories;
    }

    /**
     * Generated from protobuf field <code>bool seen_all_group_stories = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setSeenAllGroupStories($var)
    {
        GPBUtil::checkBool($var);
        $this->seen_all_group_stories = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Story stories = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStories()
    {
        return $this->stories;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Story stories = 5;</code>
     * @param array<\Proto\Story>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStories($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Story::class);
        $this->stories = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool self = 6;</code>
     * @return bool
     */
    public function getSelf()
    {
        return $this->self;
    }

    /**
     * Generated from protobuf field <code>bool self = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setSelf($var)
    {
        GPBUtil::checkBool($var);
        $this->self = $var;

        return $this;
    }

}

