<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>proto.Language</code>
 */
class Language
{
    /**
     * Generated from protobuf enum <code>EN_US = 0;</code>
     */
    const EN_US = 0;
    /**
     * Generated from protobuf enum <code>FA_IR = 1;</code>
     */
    const FA_IR = 1;

    private static $valueToName = [
        self::EN_US => 'EN_US',
        self::FA_IR => 'FA_IR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

