<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PollField</code>
 */
class PollField extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string imageurl = 1;</code>
     */
    protected $imageurl = '';
    /**
     * Generated from protobuf field <code>uint32 orderid = 2;</code>
     */
    protected $orderid = 0;
    /**
     * Generated from protobuf field <code>uint32 id = 3;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>bool clicked = 4;</code>
     */
    protected $clicked = false;
    /**
     * Generated from protobuf field <code>uint64 sum = 5 [jstype = JS_STRING];</code>
     */
    protected $sum = 0;
    /**
     * Generated from protobuf field <code>bool clickable = 6;</code>
     */
    protected $clickable = false;
    /**
     * Generated from protobuf field <code>string label = 7;</code>
     */
    protected $label = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $imageurl
     *     @type int $orderid
     *     @type int $id
     *     @type bool $clicked
     *     @type int|string $sum
     *     @type bool $clickable
     *     @type string $label
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBGlobal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string imageurl = 1;</code>
     * @return string
     */
    public function getImageurl()
    {
        return $this->imageurl;
    }

    /**
     * Generated from protobuf field <code>string imageurl = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setImageurl($var)
    {
        GPBUtil::checkString($var, True);
        $this->imageurl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 orderid = 2;</code>
     * @return int
     */
    public function getOrderid()
    {
        return $this->orderid;
    }

    /**
     * Generated from protobuf field <code>uint32 orderid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderid($var)
    {
        GPBUtil::checkUint32($var);
        $this->orderid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 3;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool clicked = 4;</code>
     * @return bool
     */
    public function getClicked()
    {
        return $this->clicked;
    }

    /**
     * Generated from protobuf field <code>bool clicked = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setClicked($var)
    {
        GPBUtil::checkBool($var);
        $this->clicked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 sum = 5 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getSum()
    {
        return $this->sum;
    }

    /**
     * Generated from protobuf field <code>uint64 sum = 5 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setSum($var)
    {
        GPBUtil::checkUint64($var);
        $this->sum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool clickable = 6;</code>
     * @return bool
     */
    public function getClickable()
    {
        return $this->clickable;
    }

    /**
     * Generated from protobuf field <code>bool clickable = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setClickable($var)
    {
        GPBUtil::checkBool($var);
        $this->clickable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string label = 7;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

}

