<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>proto.RoomMessageStatus</code>
 */
class RoomMessageStatus
{
    /**
     * Generated from protobuf enum <code>FAILED = 0;</code>
     */
    const FAILED = 0;
    /**
     * Generated from protobuf enum <code>SENDING = 1;</code>
     */
    const SENDING = 1;
    /**
     * Generated from protobuf enum <code>SENT = 2;</code>
     */
    const SENT = 2;
    /**
     * Generated from protobuf enum <code>DELIVERED = 3;</code>
     */
    const DELIVERED = 3;
    /**
     * Generated from protobuf enum <code>SEEN = 4;</code>
     */
    const SEEN = 4;
    /**
     * Generated from protobuf enum <code>LISTENED = 5;</code>
     */
    const LISTENED = 5;

    private static $valueToName = [
        self::FAILED => 'FAILED',
        self::SENDING => 'SENDING',
        self::SENT => 'SENT',
        self::DELIVERED => 'DELIVERED',
        self::SEEN => 'SEEN',
        self::LISTENED => 'LISTENED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

