<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.RoomAccess</code>
 */
class RoomAccess extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool modify_room = 1;</code>
     */
    protected $modify_room = false;
    /**
     * Generated from protobuf field <code>.proto.PostMessageRights post_message = 2;</code>
     */
    protected $post_message = null;
    /**
     * Generated from protobuf field <code>bool edit_message = 3;</code>
     */
    protected $edit_message = false;
    /**
     * Generated from protobuf field <code>bool delete_message = 4;</code>
     */
    protected $delete_message = false;
    /**
     * Generated from protobuf field <code>bool pin_message = 5;</code>
     */
    protected $pin_message = false;
    /**
     * Generated from protobuf field <code>bool add_member = 6;</code>
     */
    protected $add_member = false;
    /**
     * Generated from protobuf field <code>bool ban_member = 7;</code>
     */
    protected $ban_member = false;
    /**
     * Generated from protobuf field <code>bool get_member = 8;</code>
     */
    protected $get_member = false;
    /**
     * Generated from protobuf field <code>bool add_admin = 9;</code>
     */
    protected $add_admin = false;
    /**
     * Generated from protobuf field <code>bool add_story = 10;</code>
     */
    protected $add_story = false;
    /**
     * Generated from protobuf field <code>bool delete_story = 11;</code>
     */
    protected $delete_story = false;
    /**
     * Generated from protobuf field <code>bool show_story_views = 12;</code>
     */
    protected $show_story_views = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $modify_room
     *     @type \Proto\PostMessageRights $post_message
     *     @type bool $edit_message
     *     @type bool $delete_message
     *     @type bool $pin_message
     *     @type bool $add_member
     *     @type bool $ban_member
     *     @type bool $get_member
     *     @type bool $add_admin
     *     @type bool $add_story
     *     @type bool $delete_story
     *     @type bool $show_story_views
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBGlobal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool modify_room = 1;</code>
     * @return bool
     */
    public function getModifyRoom()
    {
        return $this->modify_room;
    }

    /**
     * Generated from protobuf field <code>bool modify_room = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setModifyRoom($var)
    {
        GPBUtil::checkBool($var);
        $this->modify_room = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.PostMessageRights post_message = 2;</code>
     * @return \Proto\PostMessageRights|null
     */
    public function getPostMessage()
    {
        return $this->post_message;
    }

    public function hasPostMessage()
    {
        return isset($this->post_message);
    }

    public function clearPostMessage()
    {
        unset($this->post_message);
    }

    /**
     * Generated from protobuf field <code>.proto.PostMessageRights post_message = 2;</code>
     * @param \Proto\PostMessageRights $var
     * @return $this
     */
    public function setPostMessage($var)
    {
        GPBUtil::checkMessage($var, \Proto\PostMessageRights::class);
        $this->post_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool edit_message = 3;</code>
     * @return bool
     */
    public function getEditMessage()
    {
        return $this->edit_message;
    }

    /**
     * Generated from protobuf field <code>bool edit_message = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setEditMessage($var)
    {
        GPBUtil::checkBool($var);
        $this->edit_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool delete_message = 4;</code>
     * @return bool
     */
    public function getDeleteMessage()
    {
        return $this->delete_message;
    }

    /**
     * Generated from protobuf field <code>bool delete_message = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeleteMessage($var)
    {
        GPBUtil::checkBool($var);
        $this->delete_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool pin_message = 5;</code>
     * @return bool
     */
    public function getPinMessage()
    {
        return $this->pin_message;
    }

    /**
     * Generated from protobuf field <code>bool pin_message = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setPinMessage($var)
    {
        GPBUtil::checkBool($var);
        $this->pin_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool add_member = 6;</code>
     * @return bool
     */
    public function getAddMember()
    {
        return $this->add_member;
    }

    /**
     * Generated from protobuf field <code>bool add_member = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setAddMember($var)
    {
        GPBUtil::checkBool($var);
        $this->add_member = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ban_member = 7;</code>
     * @return bool
     */
    public function getBanMember()
    {
        return $this->ban_member;
    }

    /**
     * Generated from protobuf field <code>bool ban_member = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setBanMember($var)
    {
        GPBUtil::checkBool($var);
        $this->ban_member = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool get_member = 8;</code>
     * @return bool
     */
    public function getGetMember()
    {
        return $this->get_member;
    }

    /**
     * Generated from protobuf field <code>bool get_member = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setGetMember($var)
    {
        GPBUtil::checkBool($var);
        $this->get_member = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool add_admin = 9;</code>
     * @return bool
     */
    public function getAddAdmin()
    {
        return $this->add_admin;
    }

    /**
     * Generated from protobuf field <code>bool add_admin = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setAddAdmin($var)
    {
        GPBUtil::checkBool($var);
        $this->add_admin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool add_story = 10;</code>
     * @return bool
     */
    public function getAddStory()
    {
        return $this->add_story;
    }

    /**
     * Generated from protobuf field <code>bool add_story = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setAddStory($var)
    {
        GPBUtil::checkBool($var);
        $this->add_story = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool delete_story = 11;</code>
     * @return bool
     */
    public function getDeleteStory()
    {
        return $this->delete_story;
    }

    /**
     * Generated from protobuf field <code>bool delete_story = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeleteStory($var)
    {
        GPBUtil::checkBool($var);
        $this->delete_story = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool show_story_views = 12;</code>
     * @return bool
     */
    public function getShowStoryViews()
    {
        return $this->show_story_views;
    }

    /**
     * Generated from protobuf field <code>bool show_story_views = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setShowStoryViews($var)
    {
        GPBUtil::checkBool($var);
        $this->show_story_views = $var;

        return $this;
    }

}

