<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalingClearLog.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.SignalingClearLogResponse</code>
 */
class SignalingClearLogResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    protected $response = null;
    /**
     * Generated from protobuf field <code>uint64 clear_id = 2;</code>
     */
    protected $clear_id = 0;
    /**
     * Generated from protobuf field <code>repeated uint64 log_id = 3;</code>
     */
    private $log_id;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type int|string $clear_id
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $log_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SignalingClearLog::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response|null
     */
    public function getResponse()
    {
        return $this->response;
    }

    public function hasResponse()
    {
        return isset($this->response);
    }

    public function clearResponse()
    {
        unset($this->response);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 clear_id = 2;</code>
     * @return int|string
     */
    public function getClearId()
    {
        return $this->clear_id;
    }

    /**
     * Generated from protobuf field <code>uint64 clear_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClearId($var)
    {
        GPBUtil::checkUint64($var);
        $this->clear_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 log_id = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogId()
    {
        return $this->log_id;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 log_id = 3;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->log_id = $arr;

        return $this;
    }

}

