<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MxbUser.proto

namespace Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>proto.StatusAction</code>
 */
class StatusAction
{
    /**
     * Generated from protobuf enum <code>ACTIVATE = 0;</code>
     */
    const ACTIVATE = 0;
    /**
     * Generated from protobuf enum <code>DEACTIVATE = 1;</code>
     */
    const DEACTIVATE = 1;

    private static $valueToName = [
        self::ACTIVATE => 'ACTIVATE',
        self::DEACTIVATE => 'DEACTIVATE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

