<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Story</code>
 */
class Story extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1 [jstype = JS_STRING];</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string file_token = 2;</code>
     */
    protected $file_token = '';
    /**
     * Generated from protobuf field <code>.proto.File file_details = 3;</code>
     */
    protected $file_details = null;
    /**
     * Generated from protobuf field <code>.proto.Story.Type type = 4;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>uint64 user_id = 5 [jstype = JS_STRING];</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>uint64 room_id = 6 [jstype = JS_STRING];</code>
     */
    protected $room_id = 0;
    /**
     * Generated from protobuf field <code>string caption = 7;</code>
     */
    protected $caption = '';
    /**
     * Generated from protobuf field <code>string link = 8;</code>
     */
    protected $link = '';
    /**
     * Generated from protobuf field <code>uint32 created_at = 9;</code>
     */
    protected $created_at = 0;
    /**
     * Generated from protobuf field <code>uint32 end_at = 10;</code>
     */
    protected $end_at = 0;
    /**
     * Generated from protobuf field <code>bool seen = 11;</code>
     */
    protected $seen = false;
    /**
     * Generated from protobuf field <code>bool duplicated = 12;</code>
     */
    protected $duplicated = false;
    /**
     * Generated from protobuf field <code>.proto.Originator originator = 13;</code>
     */
    protected $originator = 0;
    /**
     * Generated from protobuf field <code>uint32 views = 14;</code>
     */
    protected $views = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $file_token
     *     @type \Proto\File $file_details
     *     @type int $type
     *     @type int|string $user_id
     *     @type int|string $room_id
     *     @type string $caption
     *     @type string $link
     *     @type int $created_at
     *     @type int $end_at
     *     @type bool $seen
     *     @type bool $duplicated
     *     @type int $originator
     *     @type int $views
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBGlobal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string file_token = 2;</code>
     * @return string
     */
    public function getFileToken()
    {
        return $this->file_token;
    }

    /**
     * Generated from protobuf field <code>string file_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFileToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->file_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.File file_details = 3;</code>
     * @return \Proto\File|null
     */
    public function getFileDetails()
    {
        return $this->file_details;
    }

    public function hasFileDetails()
    {
        return isset($this->file_details);
    }

    public function clearFileDetails()
    {
        unset($this->file_details);
    }

    /**
     * Generated from protobuf field <code>.proto.File file_details = 3;</code>
     * @param \Proto\File $var
     * @return $this
     */
    public function setFileDetails($var)
    {
        GPBUtil::checkMessage($var, \Proto\File::class);
        $this->file_details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Story.Type type = 4;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.proto.Story.Type type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Proto\Story\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 5 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 5 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 room_id = 6 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * Generated from protobuf field <code>uint64 room_id = 6 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkUint64($var);
        $this->room_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string caption = 7;</code>
     * @return string
     */
    public function getCaption()
    {
        return $this->caption;
    }

    /**
     * Generated from protobuf field <code>string caption = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCaption($var)
    {
        GPBUtil::checkString($var, True);
        $this->caption = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string link = 8;</code>
     * @return string
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Generated from protobuf field <code>string link = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->link = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 created_at = 9;</code>
     * @return int
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>uint32 created_at = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkUint32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 end_at = 10;</code>
     * @return int
     */
    public function getEndAt()
    {
        return $this->end_at;
    }

    /**
     * Generated from protobuf field <code>uint32 end_at = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setEndAt($var)
    {
        GPBUtil::checkUint32($var);
        $this->end_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool seen = 11;</code>
     * @return bool
     */
    public function getSeen()
    {
        return $this->seen;
    }

    /**
     * Generated from protobuf field <code>bool seen = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setSeen($var)
    {
        GPBUtil::checkBool($var);
        $this->seen = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool duplicated = 12;</code>
     * @return bool
     */
    public function getDuplicated()
    {
        return $this->duplicated;
    }

    /**
     * Generated from protobuf field <code>bool duplicated = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setDuplicated($var)
    {
        GPBUtil::checkBool($var);
        $this->duplicated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Originator originator = 13;</code>
     * @return int
     */
    public function getOriginator()
    {
        return $this->originator;
    }

    /**
     * Generated from protobuf field <code>.proto.Originator originator = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setOriginator($var)
    {
        GPBUtil::checkEnum($var, \Proto\Originator::class);
        $this->originator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 views = 14;</code>
     * @return int
     */
    public function getViews()
    {
        return $this->views;
    }

    /**
     * Generated from protobuf field <code>uint32 views = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setViews($var)
    {
        GPBUtil::checkUint32($var);
        $this->views = $var;

        return $this;
    }

}

