<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StoryGetOwnStoryViews.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.StoryGetOwnStoryViewsResponse</code>
 */
class StoryGetOwnStoryViewsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    protected $response = null;
    /**
     * Generated from protobuf field <code>repeated .proto.GroupedViews grouped_views = 3;</code>
     */
    private $grouped_views;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type array<\Proto\GroupedViews>|\Google\Protobuf\Internal\RepeatedField $grouped_views
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StoryGetOwnStoryViews::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response|null
     */
    public function getResponse()
    {
        return $this->response;
    }

    public function hasResponse()
    {
        return isset($this->response);
    }

    public function clearResponse()
    {
        unset($this->response);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.GroupedViews grouped_views = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroupedViews()
    {
        return $this->grouped_views;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.GroupedViews grouped_views = 3;</code>
     * @param array<\Proto\GroupedViews>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroupedViews($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\GroupedViews::class);
        $this->grouped_views = $arr;

        return $this;
    }

}

