<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StoryRoomAddNew.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.StoryRoomAddNewResponse</code>
 */
class StoryRoomAddNewResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    protected $response = null;
    /**
     * Generated from protobuf field <code>repeated .proto.Story story = 2;</code>
     */
    private $story;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type array<\Proto\Story>|\Google\Protobuf\Internal\RepeatedField $story
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StoryRoomAddNew::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response|null
     */
    public function getResponse()
    {
        return $this->response;
    }

    public function hasResponse()
    {
        return isset($this->response);
    }

    public function clearResponse()
    {
        unset($this->response);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Story story = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStory()
    {
        return $this->story;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Story story = 2;</code>
     * @param array<\Proto\Story>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStory($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Story::class);
        $this->story = $arr;

        return $this;
    }

}

