<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StoryUserAddNew.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.StoryUserAddNew</code>
 */
class StoryUserAddNew extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     */
    protected $request = null;
    /**
     * Generated from protobuf field <code>repeated .proto.StoryAddRequest token_batch = 2;</code>
     */
    private $token_batch;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Request $request
     *     @type array<\Proto\StoryAddRequest>|\Google\Protobuf\Internal\RepeatedField $token_batch
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StoryUserAddNew::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @return \Proto\Request|null
     */
    public function getRequest()
    {
        return $this->request;
    }

    public function hasRequest()
    {
        return isset($this->request);
    }

    public function clearRequest()
    {
        unset($this->request);
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @param \Proto\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Proto\Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.StoryAddRequest token_batch = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTokenBatch()
    {
        return $this->token_batch;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.StoryAddRequest token_batch = 2;</code>
     * @param array<\Proto\StoryAddRequest>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTokenBatch($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\StoryAddRequest::class);
        $this->token_batch = $arr;

        return $this;
    }

}

