<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserVerify.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserVerify</code>
 */
class UserVerify extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     */
    protected $request = null;
    /**
     * Generated from protobuf field <code>uint32 code = 2;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string username = 3;</code>
     */
    protected $username = '';
    /**
     * Generated from protobuf field <code>string phone_hash = 4;</code>
     */
    protected $phone_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Request $request
     *     @type int $code
     *     @type string $username
     *     @type string $phone_hash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserVerify::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @return \Proto\Request|null
     */
    public function getRequest()
    {
        return $this->request;
    }

    public function hasRequest()
    {
        return isset($this->request);
    }

    public function clearRequest()
    {
        unset($this->request);
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @param \Proto\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Proto\Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 code = 2;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>uint32 code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 3;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone_hash = 4;</code>
     * @return string
     */
    public function getPhoneHash()
    {
        return $this->phone_hash;
    }

    /**
     * Generated from protobuf field <code>string phone_hash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone_hash = $var;

        return $this;
    }

}

