<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserIVandSetActivity.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserIVandSetActivity</code>
 */
class UserIVandSetActivity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     */
    protected $request = null;
    /**
     * Generated from protobuf field <code>string plancode = 2;</code>
     */
    protected $plancode = '';
    /**
     * Generated from protobuf field <code>uint64 value = 3;</code>
     */
    protected $value = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Request $request
     *     @type string $plancode
     *     @type int|string $value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserIVandSetActivity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @return \Proto\Request|null
     */
    public function getRequest()
    {
        return $this->request;
    }

    public function hasRequest()
    {
        return isset($this->request);
    }

    public function clearRequest()
    {
        unset($this->request);
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @param \Proto\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Proto\Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string plancode = 2;</code>
     * @return string
     */
    public function getPlancode()
    {
        return $this->plancode;
    }

    /**
     * Generated from protobuf field <code>string plancode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPlancode($var)
    {
        GPBUtil::checkString($var, True);
        $this->plancode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 value = 3;</code>
     * @return int|string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>uint64 value = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkUint64($var);
        $this->value = $var;

        return $this;
    }

}

