<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelGetMessagesStats.proto

namespace Proto\ChannelGetMessagesStats;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ChannelGetMessagesStats.messageIdInfo</code>
 */
class messageIdInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 message_id = 1;</code>
     */
    protected $message_id = 0;
    /**
     * Generated from protobuf field <code>uint64 document_id = 2;</code>
     */
    protected $document_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $message_id
     *     @type int|string $document_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ChannelGetMessagesStats::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 message_id = 1;</code>
     * @return int|string
     */
    public function getMessageId()
    {
        return $this->message_id;
    }

    /**
     * Generated from protobuf field <code>uint64 message_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkUint64($var);
        $this->message_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 document_id = 2;</code>
     * @return int|string
     */
    public function getDocumentId()
    {
        return $this->document_id;
    }

    /**
     * Generated from protobuf field <code>uint64 document_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDocumentId($var)
    {
        GPBUtil::checkUint64($var);
        $this->document_id = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(messageIdInfo::class, \Proto\ChannelGetMessagesStats_messageIdInfo::class);

