<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto\RoomMessageLog;

use UnexpectedValueException;

/**
 * Protobuf type <code>proto.RoomMessageLog.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>USER_JOINED = 0;</code>
     */
    const USER_JOINED = 0;
    /**
     * Generated from protobuf enum <code>USER_DELETED = 1;</code>
     */
    const USER_DELETED = 1;
    /**
     * Generated from protobuf enum <code>ROOM_CREATED = 2;</code>
     */
    const ROOM_CREATED = 2;
    /**
     * Generated from protobuf enum <code>MEMBER_ADDED = 3;</code>
     */
    const MEMBER_ADDED = 3;
    /**
     * Generated from protobuf enum <code>MEMBER_KICKED = 4;</code>
     */
    const MEMBER_KICKED = 4;
    /**
     * Generated from protobuf enum <code>MEMBER_LEFT = 5;</code>
     */
    const MEMBER_LEFT = 5;
    /**
     * Generated from protobuf enum <code>ROOM_CONVERTED_TO_PUBLIC = 6;</code>
     */
    const ROOM_CONVERTED_TO_PUBLIC = 6;
    /**
     * Generated from protobuf enum <code>ROOM_CONVERTED_TO_PRIVATE = 7;</code>
     */
    const ROOM_CONVERTED_TO_PRIVATE = 7;
    /**
     * Generated from protobuf enum <code>MEMBER_JOINED_BY_INVITE_LINK = 8;</code>
     */
    const MEMBER_JOINED_BY_INVITE_LINK = 8;
    /**
     * Generated from protobuf enum <code>ROOM_DELETED = 9;</code>
     */
    const ROOM_DELETED = 9;
    /**
     * Generated from protobuf enum <code>MISSED_VOICE_CALL = 10;</code>
     */
    const MISSED_VOICE_CALL = 10;
    /**
     * Generated from protobuf enum <code>MISSED_VIDEO_CALL = 11;</code>
     */
    const MISSED_VIDEO_CALL = 11;
    /**
     * Generated from protobuf enum <code>MISSED_SCREEN_SHARE = 12;</code>
     */
    const MISSED_SCREEN_SHARE = 12;
    /**
     * Generated from protobuf enum <code>MISSED_SECRET_CHAT = 13;</code>
     */
    const MISSED_SECRET_CHAT = 13;
    /**
     * Generated from protobuf enum <code>PINNED_MESSAGE = 14;</code>
     */
    const PINNED_MESSAGE = 14;
    /**
     * Generated from protobuf enum <code>CHANGE_PHONE_NUMBER = 15;</code>
     */
    const CHANGE_PHONE_NUMBER = 15;

    private static $valueToName = [
        self::USER_JOINED => 'USER_JOINED',
        self::USER_DELETED => 'USER_DELETED',
        self::ROOM_CREATED => 'ROOM_CREATED',
        self::MEMBER_ADDED => 'MEMBER_ADDED',
        self::MEMBER_KICKED => 'MEMBER_KICKED',
        self::MEMBER_LEFT => 'MEMBER_LEFT',
        self::ROOM_CONVERTED_TO_PUBLIC => 'ROOM_CONVERTED_TO_PUBLIC',
        self::ROOM_CONVERTED_TO_PRIVATE => 'ROOM_CONVERTED_TO_PRIVATE',
        self::MEMBER_JOINED_BY_INVITE_LINK => 'MEMBER_JOINED_BY_INVITE_LINK',
        self::ROOM_DELETED => 'ROOM_DELETED',
        self::MISSED_VOICE_CALL => 'MISSED_VOICE_CALL',
        self::MISSED_VIDEO_CALL => 'MISSED_VIDEO_CALL',
        self::MISSED_SCREEN_SHARE => 'MISSED_SCREEN_SHARE',
        self::MISSED_SECRET_CHAT => 'MISSED_SECRET_CHAT',
        self::PINNED_MESSAGE => 'PINNED_MESSAGE',
        self::CHANGE_PHONE_NUMBER => 'CHANGE_PHONE_NUMBER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Proto\RoomMessageLog_Type::class);

