<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto\RoomMessage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.RoomMessage.Author</code>
 */
class Author extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string hash = 1;</code>
     */
    protected $hash = '';
    /**
     * Generated from protobuf field <code>.proto.RoomMessage.Author.User user = 2;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>.proto.RoomMessage.Author.Room room = 3;</code>
     */
    protected $room = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hash
     *     @type \Proto\RoomMessage\Author\User $user
     *     @type \Proto\RoomMessage\Author\Room $room
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBGlobal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string hash = 1;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>string hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage.Author.User user = 2;</code>
     * @return \Proto\RoomMessage\Author\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage.Author.User user = 2;</code>
     * @param \Proto\RoomMessage\Author\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Proto\RoomMessage\Author\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage.Author.Room room = 3;</code>
     * @return \Proto\RoomMessage\Author\Room|null
     */
    public function getRoom()
    {
        return $this->room;
    }

    public function hasRoom()
    {
        return isset($this->room);
    }

    public function clearRoom()
    {
        unset($this->room);
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage.Author.Room room = 3;</code>
     * @param \Proto\RoomMessage\Author\Room $var
     * @return $this
     */
    public function setRoom($var)
    {
        GPBUtil::checkMessage($var, \Proto\RoomMessage\Author\Room::class);
        $this->room = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Author::class, \Proto\RoomMessage_Author::class);

