<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupChangeMemberRights.proto

namespace Proto\GroupChangeMemberRights;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.GroupChangeMemberRights.MemberRights</code>
 */
class MemberRights extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool send_text = 1;</code>
     */
    protected $send_text = false;
    /**
     * Generated from protobuf field <code>bool send_media = 3;</code>
     */
    protected $send_media = false;
    /**
     * Generated from protobuf field <code>bool send_gif = 4;</code>
     */
    protected $send_gif = false;
    /**
     * Generated from protobuf field <code>bool send_sticker = 5;</code>
     */
    protected $send_sticker = false;
    /**
     * Generated from protobuf field <code>bool send_link = 6;</code>
     */
    protected $send_link = false;
    /**
     * Generated from protobuf field <code>bool pin_message = 7;</code>
     */
    protected $pin_message = false;
    /**
     * Generated from protobuf field <code>bool add_member = 8;</code>
     */
    protected $add_member = false;
    /**
     * Generated from protobuf field <code>bool get_member = 9;</code>
     */
    protected $get_member = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $send_text
     *     @type bool $send_media
     *     @type bool $send_gif
     *     @type bool $send_sticker
     *     @type bool $send_link
     *     @type bool $pin_message
     *     @type bool $add_member
     *     @type bool $get_member
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GroupChangeMemberRights::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool send_text = 1;</code>
     * @return bool
     */
    public function getSendText()
    {
        return $this->send_text;
    }

    /**
     * Generated from protobuf field <code>bool send_text = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSendText($var)
    {
        GPBUtil::checkBool($var);
        $this->send_text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool send_media = 3;</code>
     * @return bool
     */
    public function getSendMedia()
    {
        return $this->send_media;
    }

    /**
     * Generated from protobuf field <code>bool send_media = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setSendMedia($var)
    {
        GPBUtil::checkBool($var);
        $this->send_media = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool send_gif = 4;</code>
     * @return bool
     */
    public function getSendGif()
    {
        return $this->send_gif;
    }

    /**
     * Generated from protobuf field <code>bool send_gif = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setSendGif($var)
    {
        GPBUtil::checkBool($var);
        $this->send_gif = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool send_sticker = 5;</code>
     * @return bool
     */
    public function getSendSticker()
    {
        return $this->send_sticker;
    }

    /**
     * Generated from protobuf field <code>bool send_sticker = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setSendSticker($var)
    {
        GPBUtil::checkBool($var);
        $this->send_sticker = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool send_link = 6;</code>
     * @return bool
     */
    public function getSendLink()
    {
        return $this->send_link;
    }

    /**
     * Generated from protobuf field <code>bool send_link = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setSendLink($var)
    {
        GPBUtil::checkBool($var);
        $this->send_link = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool pin_message = 7;</code>
     * @return bool
     */
    public function getPinMessage()
    {
        return $this->pin_message;
    }

    /**
     * Generated from protobuf field <code>bool pin_message = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setPinMessage($var)
    {
        GPBUtil::checkBool($var);
        $this->pin_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool add_member = 8;</code>
     * @return bool
     */
    public function getAddMember()
    {
        return $this->add_member;
    }

    /**
     * Generated from protobuf field <code>bool add_member = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setAddMember($var)
    {
        GPBUtil::checkBool($var);
        $this->add_member = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool get_member = 9;</code>
     * @return bool
     */
    public function getGetMember()
    {
        return $this->get_member;
    }

    /**
     * Generated from protobuf field <code>bool get_member = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setGetMember($var)
    {
        GPBUtil::checkBool($var);
        $this->get_member = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(MemberRights::class, \Proto\GroupChangeMemberRights_MemberRights::class);

