<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserReport.proto

namespace Proto\UserReport;

use UnexpectedValueException;

/**
 * Protobuf type <code>proto.UserReport.Reason</code>
 */
class Reason
{
    /**
     * Generated from protobuf enum <code>OTHER = 0;</code>
     */
    const OTHER = 0;
    /**
     * Generated from protobuf enum <code>SPAM = 1;</code>
     */
    const SPAM = 1;
    /**
     * Generated from protobuf enum <code>ABUSE = 2;</code>
     */
    const ABUSE = 2;
    /**
     * Generated from protobuf enum <code>FAKE_ACCOUNT = 3;</code>
     */
    const FAKE_ACCOUNT = 3;

    private static $valueToName = [
        self::OTHER => 'OTHER',
        self::SPAM => 'SPAM',
        self::ABUSE => 'ABUSE',
        self::FAKE_ACCOUNT => 'FAKE_ACCOUNT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Reason::class, \Proto\UserReport_Reason::class);

