<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdui.proto

namespace App\Core\Grpc\GPBMetadata;

class Sdui
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        \App\Core\Grpc\GPBMetadata\Enum::initOnce();
        $pool->internalAddGeneratedFile(
            '
�

sdui.protoir.kalabazzar.proto"~
GetSduiRequest
path (	+
type (2.ir.kalabazzar.proto.SduiType1
project (2 .ir.kalabazzar.proto.SduiProject"E
GetSduiResponse
status_code (
message (	
data (	2c
SduiServiceT
GetSdui#.ir.kalabazzar.proto.GetSduiRequest$.ir.kalabazzar.proto.GetSduiResponseB>Z%gitlab.com/saeedhpro/goutils/gen/sdui�App\\Core\\Grpc\\Modelsbproto3'
            , true);

        static::$is_initialized = true;
    }
}

