<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InfoConfig.proto

namespace Proto\MicroService;

use UnexpectedValueException;

/**
 * Protobuf type <code>proto.MicroService.ConnectionType</code>
 */
class ConnectionType
{
    /**
     * Generated from protobuf enum <code>HTTPS = 0;</code>
     */
    const HTTPS = 0;
    /**
     * Generated from protobuf enum <code>SOCKET = 1;</code>
     */
    const SOCKET = 1;

    private static $valueToName = [
        self::HTTPS => 'HTTPS',
        self::SOCKET => 'SOCKET',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ConnectionType::class, \Proto\MicroService_ConnectionType::class);

